### ISSUE TITLE
IMEV MIM conform maken

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/imev-werkomgeving#1]
IMEV moet MIM conform worden. Dit is handwerk

**Comment by PalmJanssen** [comment]
gaan we doen

**Comment by BrittvanWaveren** [comment]
Beste Paul, hierbij zoals verzocht de reactie van Geodan:

Technische impact: Als gevolg van deze wijziging moet de API specificatie generator aangepast worden. Nu is het gebruik van de metagegevens in het IMEV niet erg consistent. Het zou goed zijn als hier een standaard in gevolgd wordt, zodat we voortaan beter weten wat we in het IMEV kunnen verwachten.
