### ISSUE TITLE
Wijziging enumerartion Representatielijn: hartlijn moet 'referentiepunt plaatsgebonden risico' worden

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#10]
nr in eerste issuelijst: 9
Indiener: Ruben Polman (RWS)

In de IMEV voor wegvervoer op REV.nl staat onder enumeration onderdelen: Representatielijn het volgende:

-  hartlijn
-  kantstreep
-  oeverlijn
-  buitensteSpoor
-  kantVerharding
-  basisnet

Dit is doorvertaald naar het datamodel. In het veld typeplaatsgebondenrisico moet één van de genoemde waarden worden ingevuld.

Inmiddels is uit de conceptversie van het gegevenswoordenboek gebleken dat de term Hartlijn gekozen moet worden. 
Dit is niet handig. De term Hartlijn komt niet voor in  regelgeving rondom externe veiligheid basisnet. 
Deze term komt wel voor in het NWB en wordt gebruikt bij geluidcontouren, 
maar daar wordt een andere lijn bedoeld dan bij externe veiligheid. 
Dit zorgt voor verwarring. De Hartlijn is het midden tussen de binnenste en de buitenste kantstreep van de weg. 
Dit is niet hetzelfde als het referentiepunt voor het plaatsgebonden risico als bedoeld in art 3 van de Regeling basisnet. 
Voorstel is om in plaats van Hartlijn hier “referentiepunt plaatsgebonden risico” in te vullen. 

**Analyse/Oplossing**
Met de representatielijn wordt aangegeven wat de de lijn die als referentiepunt dient voorsteld. Afhankelijk hoe er gerekend wordt kan dit verschillen.
Het wijzigen van een representatielijn naar 'referentiepunt plaatsgebonden risico'lijkt dan ook niet logisch. Dit is de beschrijving van het object waar dit een kenmerk van is. 

een goede term voor "het midden tussen de binnenste en de buitenste kantstreep van de weg" bedenken lijkt een betere optie hier.

**Comment by PalmJanssen** [comment]
dit is wat BRT zegt over hartlijn van wegen:
![image](https://user-images.githubusercontent.com/9932784/125766816-9fe36b0e-2a46-4f11-a843-2ddb55611e68.png)

**Comment by BrittvanWaveren** [comment]
Beste Paul, hierbij zoals verzocht de reactie van Geodan:

Technische impact: het aanpassen van de enumeratie betekent dat we de REV API specificatie moeten aanpassen.

**Comment by PalmJanssen** [comment]
In onderzoek bij RWS (?)

**Comment by PB-GNM** [comment]
Voorstel Peter Winkelman en Taco Kooistra: waarde wordt: "referentielijnWeg" ipv "hartlijn"
@Ruben: zou je hier dan nog een goede omschrijving voor willen geven voor in het gegevenswoordenboek.

**Comment by RubenPolman** [comment]
Voorstel: De referentielijnWeg is het samenstel van de referentiepunten als bedoeld in de Regeling basisnet artikel 3.
(Dit is het midden van de middenberm met de volgende afwijkingen:
 - het midden tussen de buitenste kantstrepen van de doorgaande rijbaan indien de betrokken weg is bedoeld voor éénrichtingsverkeer of indien de middenberm breder is dan 25 meter.
 - de scheiding van de rijrichtingen indien het een weg zonder middenberm met twee rijrichtingen betreft. )

**Comment by PalmJanssen** [comment]
Verwerkt.

Was:
hartlijn: definitie:
het midden van de weg/scheiding tussen rijrichtingen; of midden tussen de buitenste kantstrepen bij eenrichtingsverkeer

Wordt:
referentielijnWeg: definitie:
De referentielijnWeg is het samenstel van de referentiepunten als bedoeld in de Regeling basisnet artikel 3.
Dit is het midden van de middenberm met de volgende afwijkingen:

- het midden tussen de buitenste kantstrepen van de doorgaande rijbaan indien de betrokken weg is bedoeld voor éénrichtingsverkeer of indien de middenberm breder is dan 25 meter.
- de scheiding van de rijrichtingen indien het een weg zonder middenberm met twee rijrichtingen betreft.

Opmerking: de term hartlijn komt nog op meerdere plaatsen in definities van termen in het model voor. Dat wordt aangepast

**Comment by fzantea** [comment]
wordt hartlijn ook niet gebruikt bij SpoorVervoer? In dat geval in referentielijnWeg niet de juiste term.

**Comment by PalmJanssen** [comment]
Is er dan niet ook een referentielijnWater nodig? Zo ja, met welke definitie?
