### ISSUE TITLE
Enumeratie buisleidingCategorieStof aanpassen (SDIMEV-107, Welt ????)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#105]
## Aanleiding wijziging
Dit is meer conform Bal art. 3.101 lid 1 a t/m d

## Voorgestelde wijziging
De enumeratie was:
![image](https://github.com/Geonovum/imev-werkomgeving/assets/80040145/6ac7118a-23bc-46b9-a6fe-f31427f80886)

Het verzoek is om deze te vervangen door de volgende lijst die conform het Bal is:

- a: aardgas, 
- b1: ontvlambare gassen
- b2: ontvlambare vloeistoffen
- c: acuut toxische stoffen
- d1: kooldioxide
- d2: zuurstof
- d3: stikstof

## Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? **Dataleveranciers, Softwareleveranciers**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
- Heeft het impact op het json-schema? **Ja, want de enumeratie is onderdeel van het schema**
- Is het backwardscompatibel? **Ja, mits de waarden 1 op 1 om te zetten zijn**
- X-, Y- of Z-wijziging: **Y**

## Prioriteit
laag, midden, hoog

## Toelichting
Wat moet er met met de waarde "gegevenInTransitie" gebeuren?

**Comment by PB-GNM** [comment]
Er is een verband met PRContour.maatgevendeStof in #103 waar een StofCategorie enumeratie wordt voorgesteld.

**Comment by JanCasSmitGeonovum** [comment]
**Conclusie van Expertoverleg:**

Discussie gevoerd en t.o.v. de voorgestelde wijziging is voor een tussenoplossing gekozen die erg lijkt op de oorspronkelijke reeds in het model opgenomen lijst. 

De lijst wordt nu:

- aardgas
- ontvlambareGassenNietAardgas
- ontvlambareVloeistoffen
- acuutToxischeStoffen
- kooldioxide
- zuurstof
- stikstof
- gegevenInTransitie

In feite is alleen "acuutToxischeStoffen" een wijziging.
