### ISSUE TITLE
De enumeratie van Pipe­Material­Type­Value aanpassen (SDIMEV-107, Welt ????)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#106]
## Aanleiding wijziging
Door de verzochte aanpassing wordt de enumeratie meer conform Bal art. 4.1115 lid 2 f.

## Voorgestelde wijziging
De situatie was als in https://docs.geostandaarden.nl/imev/imev/#detail_class_Waardelijsten_PipeMaterialTypeValue

Verzocht wordt deze lijst in te korten tot:
- Koolstofstaal (CS), rekgrens Re < 415 MPa
- Koolstofstaal (CS), rekgrens Re ≥ 415 MPa
- Koolstofstaal met RVS cladding (CS+SS clad)
- Koolstofstaal, lage temperatuur (LTCS)
- Kunststof, composiet
- Kunststof, FRP
- Kunststof, GRE
- Kunststof, HDPE
- Roestvaststaal, austenitisch (SS)
- Roestvaststaal, (super)duplex (DSS)

## Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? **Dataleveranciers, Softwareleveranciers**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
- Heeft het impact op het json-schema? **Ja, want de enumeratie is onderdeel van het schema**
- Is het backwardscompatibel? **Nee, tenzij er een eenduidige transformatie van de oude waarden naar de nieuwe op te stellen is**
- X-, Y- of Z-wijziging: **X of Y**

## Prioriteit
laag, midden, hoog

## Toelichting
Is het een optie om de symbolen < en > door tekst te vervangen i.v.m. problemen rond de verwerking in software Geonovum?
De oude keuzelijst is overgenomen van Informatiemodel Kabels en Leidingen (IMKL) welke niet geschikt is voor “Buisleidingen met gevaarlijke stoffen”.
Een volledige lijst met exacte materiaalnamen is moeilijk omdat er vele materialen in gebruik zijn en nieuwe materialen bijkomen. Zou er daarom niet een waarde "overig" mogelijk gemaakt moeten worden?

**Comment by Bert-ILT** [comment]
Wijziging van de gevraagde wijziging:

Volgende waarden aanpassen:
Koolstofstaal (CS), rekgrens Re < 415 MPa  MOET ZIJN  Koolstofstaal (CS), rekgrens Re gelijk aan of kleiner dan 485 MPa
Koolstofstaal (CS), rekgrens Re ≥ 415 MPa  MOET ZIJN  Koolstofstaal (CS), rekgrens Re groter dan 485 MPa

**Comment by JanCasSmitGeonovum** [comment]
Conclusie na overleg met de expertgroep:

Koolstofstaal wordt samengevoegd tot 1 onderdeel en dan ziet de nieuwe lijst er zo uit:

- **Koolstofstaal (CS)
- Koolstofstaal met RVS cladding (CS+SS clad)
- Koolstofstaal, lage temperatuur (LTCS)
- Kunststof, composiet
- Kunststof, FRP
- Kunststof, GRE
- Kunststof, HDPE
- Roestvaststaal, austenitisch (SS)
- Roestvaststaal, (super)duplex (DSS)**

**Comment by PB-GNM** [comment]
Gezien de huidige inhoud van het REV zal "gegeveninTransitie" nog toegevoegd moeten worden anders worden 39771 records niet geconverteerd.
