### ISSUE TITLE
Verwijderen van attribuut BuisleidingReferentie.nauwkeurigheid­Bovenkantbuis (SDIMEV-107, Welt ????)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#108]
## Aanleiding wijziging
Het attribuut is onnodig en wordt niet gebruikt.

## Voorgestelde wijziging
Verwijderen van BuisleidingReferentie.nauwkeurigheidBovenkantbuis
![image](https://github.com/Geonovum/imev-werkomgeving/assets/80040145/54db34a5-bf35-4d59-999a-5b403f8ebb1c)

## Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? **Dataleveranciers, Softwareleveranciers**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
- Heeft het impact op het json-schema? **Ja**
- Is het backwardscompatibel? **Ja, mits software dit attribuut negeert bij aanleveringen die dit attribuut nog wel bevatten**
- X-, Y- of Z-wijziging: **Y**

## Prioriteit
laag, midden, hoog

## Toelichting
Ruimte voor extra toelichting. Bijvoorbeeld alternatieven die je overwogen hebt.

**Comment by JanCasSmitGeonovum** [comment]
De nauwkeurigheid bovenkant buis kan worden verwijderd.  Unaniem.
