### ISSUE TITLE
IM voor windturbines ontbreekt referenties naar de BAG

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#11]
nr in eerste issuelijst: 10
Indiener: Arno Ruijter

met de BAG 2.0 zijn windturbines nu ook ogenomen als panden en verblijfsobjecten. Volgens mij moeten we dan ook die basisregistratie referenties opnemen

**Analyse/Oplossing**
Windturbine is nu een punt in het IMEV, in de BAG een (pand)vlak geometrie kan dus nu niet direct overgenomen worden
Referenties naar BAG opnemen is denk ik wel zinvol, wellicht dan geometrie in IMEV dan ook wijzigen naar vlak, dit verzoek heb ik toegevoegd aan eerste Change Requests lijst nr 10
(niet verplichte) Identificaties Pand en/of Verblijfsobject opnemen bij Windtubine (ReferentieEVContour)

**reactie Arno:**
Als we alleen punten willen hebben voor windturbines dan zouden we ook kunnen kiezen voor het overnemen van het verblijfsobjectID, dat is een punt (en gelijk ook het adres van de windturbine)

**Comment by PalmJanssen** [comment]
uit werkgroep:
- Er zijn weinig of geen windturbines die onder de EV regels vallen en niet als pand in de bgt moeten komen.
-  veel windturbines zijn nu nog niet als bgt:pand geclassificeerd
- Maak het attribuut verplicht en voidable dan worden bronhouders meer gestuurd om het te gebruiken.

**Comment by BrittvanWaveren** [comment]
Beste Paul, hierbij zoals verzocht de reactie van Geodan:

Technische impact: De REV API specificatie moet gewijzigd worden.

**Comment by PalmJanssen** [comment]
Verwerkt.

Is nu:

![image](https://user-images.githubusercontent.com/9932784/133414010-0e50b18b-d9fe-46ac-ac51-6bb6fc234d12.png)


Met als metagegeven dat er ook een nillwaarde ingevuld mag worden.

![image](https://user-images.githubusercontent.com/9932784/133413814-20ce41f1-a2b5-4729-9e39-b1bca8da8ee0.png)

**Comment by fzantea** [comment]
Het voidable maken is ook voor andere gegevens bij andere objecttypen van belang. Als dit hier toegepast wordt dan ook bekijken waar dit nog meer toegepast kan worden. alle HR gegevens komen hier mi. ook voor in aanmerking
