### ISSUE TITLE
Toevoegen attribuut idActiviteitTR aan BKLActiviteit (SDIMEV-???, Welt-???)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#113]
## Aanleiding wijziging
Door het toevoegen van het idActiviteitTR aan de BKLActiviteit wordt het mogelijk hierop te filteren vanuit toepassingen gerelateerd aan de Omgevingswet. Deze id's worden geregistreerd in het register [Toepasbare Regels](https://omgevingswet.overheid.nl/registratie-toepasbare-regels/). Het verbetert dus de aansluiting van het REV op het Digitaal Stelsel Omgevingswet (DSO).

## Voorgestelde wijziging
Introduceer attribuut BKLActiviteit.idActiviteitTR.
Voorbeeld 1: voor een **_VII-D.2 Buisleiding met gevaarlijke stoffen_** wordt het idActiviteitTR **_[nl.imow-mnre1034.activiteit.BuisleidingGevaarlijkeStoffen](https://omgevingswet.overheid.nl/registratie-toepasbare-regels/id/nl.imow-mnre1034.activiteit.BuisleidingGevaarlijkeStoffen)_**
Voorbeeld 2: voor een **_VII-E.6 Seveso-inrichting_** wordt het idActiviteitTR **_[nl.imow-mnre1034.activiteit.SevesoInrichting](https://omgevingswet.overheid.nl/registratie-toepasbare-regels/id/nl.imow-mnre1034.activiteit.SevesoInrichting)_**

## Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? **Softwareleveranciers wel maar Dataleveranciers niet want het attribuut kan automatisch vanuit een lijst gevuld worden. Dit heeft dus wel gevolgen voor de softwareleverancier van het aanleverportaal.**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Ja/Nee**
- Heeft het impact op het json-schema? **Ja**
- Is het backwardscompatibel? **Ja, want het extra veld kan automatisch vanuit een lijst gevuld worden.**
- X-, Y- of Z-wijziging: **X**

## Prioriteit
hoog

## Toelichting
De kardinaliteit wordt 1, d.w.z. het veld wordt verplicht en er mag maar 1 idActiviteitTR gevuld worden.

**Comment by JanCasSmitGeonovum** [comment]
In de aanleiding wijziging graag in de tweede regel  de tekst "de Omgevingswet" vervangen door "het digitale stelsel Omgevingswet"
