### ISSUE TITLE
Vraag Begin-geldigheid

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#12]
Indiener:  Sasja van den Bergh, Omgevingsdienst Zuid-Hollands Zuid

**Vraag:**
In het gegevenswoordenboek staat bij de definitie van de term begin Geldigheid: Start van de periode gedurende welke deze instantie van het object geldig is in de werkelijkheid. En bij de toelichting: De geregistreerde start van de periode dat het object opgericht is in de fysieke leefomgeving.

Wat wordt er precies bedoeld met 'deze instantie van het object'? En moet er nu iets gezegd worden over wanneer het object daadwerkelijk fysiek gerealiseerd (gebouwd) is?

Stel dat ik een bestaand LPG-tankstation heb waarvoor in 1984 een oprichtingsvergunning is verleend en in 1997 een revisievergunning en daarna nog een aantal (ambtshalve) wijzigingen. Wat wordt er nu precies van mij gevraagd om in te voeren bij dit datum veld?

In het RRGS hebben wij altijd alleen de datum van de vigerende vergunning en de datum van de laatste relevante wijziging ingevoerd.

**Comment by fzantea** [comment]
Het IMEV is gebaseerd op de NEN3610. een basismodel geo-informatie. het attribuut beginGeldigheid maakt hierin deel uit van de materiële historie. Materiële historie beschrijft de veranderingen van een object in de werkelijkheid. In het IMEV staan diverse objecten, sommige met materiële historie sommige zonder. Als voorbeeld wordt een LPG tankstation genoemd. Hierbij spelen in  IMEV 4 objecttypen een rol

- EVActiviteit - De Activiteit waarvoor vergunning wordt verleend; het Tanken van LPG
- LocatieActiviteit - De plek waar de activiteit Tanken van LPG plaatsvindt
- ReferentieEVContour- Punt of vlak waarvandaan een Contour wordt berekend (bij tanken LPG bijv. Vulpuntof Tankzuil)
- EVContour- De PRcontour of het Aandachtsgebied 
Bij de EVActiviteit speelt de materiële historie géén rol, voor de overige wel. Hierbij kunnen met behulp van de materiële historie de wijziging (vanaf het ontstaan) van het object in de werkelijkheid worden bijgehouden.

**Comment by SasjaOZHZ** [comment]
Als het gaat om de materiële historie, dus wanneer iets daadwerkelijk is gerealiseerd, in plaats van wanneer iets is vergund...dan beschikken wij in veel gevallen helemaal niet over die informatie.
Het is volgens mij ook niet iets dat vanuit het Besluit kwaliteit leefomgeving wordt geeist, en het was ook geen veld dat door ons werd bijgehouden in het RRGS. Is het niet beter hier een optioneel veld van te maken in plaats van een verplicht veld? Waarom zou je een schijnnauwkeurigheid gaan creëren met een verplicht veld dat we in sommige gevallen alleen kunnen vullen met een fictieve datum?

Vriendelijke groeten, 

Sasja van den Bergh
Omgevingsdienst Zuid-Holland Zuid

**Comment by fzantea** [comment]
Nog even een aanvulling mbt waarom dit is opgenomen. Materiële historie wordt inderdaad niet geëist vanuit de BKL maar komt uit de eisen rondom de omgevingswet, het zogenaamde "tijdreizen".  Materiële (en formele) historie zijn mogelijke implementaties van tijdreizen in de NEN3610 (de basis van IMEV). Het optioneel maken kan wel maar zal dan in strijd zijn met hoe het in NEN3610 is gedefinieerd.
