### ISSUE TITLE
Waarom kent object windturbines bij EVcontouren het attribuut maatgevende risicostof?

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#15]
Indiener: Arno Ruijter
Beantwoord door: Frank Zwiers

**Vraag:**
IM voor windturbines kent bij EVcontouren de attribuut maatgevende risicostof, en dan bij waardelijst chemische bestandsdelen (zie screenshot bijlage). Dat kan ik niet plaatsen. Risico voor een windturbine is van kinetisch aard en geen chemisch risico.

**Antwoord:**
Maatgevende stof is standaard kenmerk voor deze EVcontouren (vanuit BKL), deze is niet specifiek voor Windturbines aan te passen of we moeten ervoor kiezen een specifiek EVContour maken hiervoor.

**Reactie Arno:**
Aha, maar dan zouden we als alternatief in de lijst met waarden met maatgevende stof een categorie “niet van toepassing”  moeten hebben. Hebben we die ook?  Niet gechecked

**Comment by PB-GNM** [comment]
maatgevendeStof is geen attribuut van ReferentieEVContour, maar wel van PRContour.
![image](https://user-images.githubusercontent.com/80040145/152194106-e3874a17-f049-4d5d-bd4b-96cd9cfac66b.png)
Het dus neem ik aan over het optioneel maken van het attribuut daar

**Comment by PalmJanssen** [comment]
de waarde 'niet van toepassing' ligt voor de hand

organisatie			naam		akkoord	opmerking 
Min I & W                                                x
Geodan
RWS                                                         x
Geonovum                                               x

**Comment by PalmJanssen** [comment]
Dit is met voidable opgelost:

![image](https://user-images.githubusercontent.com/9932784/157059560-7d31aa43-55e5-48cd-aae0-f2c852b44321.png)

![image](https://user-images.githubusercontent.com/9932784/157059949-462d8fec-8ebd-44c7-9155-20066cfccac2.png)
