### ISSUE TITLE
De N:M relatie tussen referentieEVcontour en EVcontour is niet duidelijk. Wanneer treedt dat op?

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#17]
Indiener: Arno Ruijter
Beantwoord door: Frank Zwiers

**Vraag:**
De N:M relatie tussen referentieEVcontour en EVcontour is niet duidelijk. Wanneer treedt dat op? Ik zou daar graag testcases voor willen laten maken.

**Antwoord:**
Een Referentie kan meerdere contouren hebben (denk aan een BrandAandachtgebied en een ExplosieAandachtgebied bij een opslagtank).
Een contour kan ook horen bij meerdere referenties, een zogenaamde barbapapa (buitenste grens van meerdere (berekende) contouren) zal horen bij meerdere referenties.
Dit pleit voor een N:M relatie.

**Reactie Arno:**
Moet hiervoor nog even in het model duiken en uitwerking hiervan. Lijkt erop dat in de JSONś het iets anders is gemodelleerd. Daar is een samengestelde referentie gemodelleerd die gekoppeld is aan meerdere referenties (heb je weer de 1:n)

**Comment by PalmJanssen** [comment]
Dit is al verwerkt
