### ISSUE TITLE
Opname Beschermingsniveau

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/imev-werkomgeving#18]
Indiener: Manuel Beterams

Beantwoord door: Frank Zwiers

**Vraag:**
Klopt het dat er in het IMEV voor de opslag van verpakte gevaarlijke stoffen met vergunningplicht (en het gegevenswoordenboek) het beschermingsniveau van de opslag niet is opgenomen?

We hebben nog naar de tabel B.3 uit het Bkl bijlage VII gekeken en in lijn met wat Wim Makaske en Hans de Waal ook hadden geconstateerd, lijkt het ons belangrijk om het beschermingsniveau toch op te nemen in het informatiemodel. 

**Antwoord:**
De keuze om dit niet oorspronkelijk niet op te nemen is wel wat te verklaren denk ik. Bij dit kenmerk is in de BKL geen enkele afstand genoemd. Dit kan je dan zien als ‘kopjes’ in de tabel.
Alle kenmerken waar een een afstand wordt bepaald staan er wel in en dat was de reden dat de lijst is opgesteld.
Rinus de Bruijne heeft het beschermingsniveau kenmerk volgens mij ook al eens benoemd in 1 van zijn mails. 
Tot zover de analyse, lijkt me dat als dit een nuttig kenmerk is dit op de changelist moet zodat het toegevoegd kan worden.

**Comment by PalmJanssen** [comment]
Bij welk object hoort dit attribuut potentieel? Bij IMEV:OpslagVerpakt_TeBerekenenAfstandVergunningsplicht

**Comment by PalmJanssen** [comment]
is dit wat er wordt bedoeld? Alle classificatie informatie is nu in het objecttype vastgelegd, inclusief het beschermingsniveau:
![image](https://user-images.githubusercontent.com/9932784/125811896-f231698b-b785-4fb7-b890-81e503086e59.png)

**Comment by BrittvanWaveren** [comment]
Beste Paul, hierbij zoals verzocht de reactie van Geodan:

Technische impact: De REV API specificatie moet gewijzigd worden.

**Comment by PB-GNM** [comment]
Bovenstaande laatste opmerking beschrijft het wijzigingsverzoek.
Deze 2 objecttypen komen voor als subtype van BLKActiviteit:
<img width="420" alt="image" src="https://user-images.githubusercontent.com/80040145/152987994-3083b8e0-de4a-4e4c-a404-201f1051e94c.png">

**Comment by PalmJanssen** [comment]
- alle beschermingsniveaus kan weg.
- alleen opnemen bij te berekenen afstanden. optioneel
- Beschermingsniveau 1: Beschermingsniveau 1 volgens PGS 15

**Comment by PalmJanssen** [comment]
Verwerkt:

![image](https://user-images.githubusercontent.com/9932784/156770749-14846821-a61b-4ac0-be7e-80accba348f9.png)

**Comment by PB-GNM** [comment]
Gesloten, omdat het verwerkt is in versie 1.2 en omdat die versie goedgekeurd is.
