### ISSUE TITLE
Verwerking aanvullende kenmerken IMEV

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/imev-werkomgeving#2]
nr in eerste issuelijst: 1
Indiender: Rinus de Bruijne DCMR

Naar   mijn mening hebben niet alle kenmerken een juiste plek in het model gekregen.   Ik ben van mening dat kenmerken die invloed uitoefenen op (de diameter van)   een contour, in het IM een plek moeten krijgen onder ‘Referentie’ en niet   onder ‘Activiteit’.

Enkele   voorbeelden :
Onder   B3 opslag bedrijf staan de kenmerken uit de tabel (voorheen Revi) nu in een   groen kader onder ‘Activiteit’. Dit levert problemen wanneer een locatie   beschikt over een loods met meerdere opslagunits van diverse omvang, die ook   nog eens voorzien kunnen zijn van verschillende blusmiddelen en   beschermingsniveaus (BN ontbreekt sowieso in het lijstje).
Naar   mijn idee hoort ‘kenmerken’ hier in een bruin kader onder ‘Referentie’ te   staan.
 
Zo is   het ook begrijpelijk dat bv ‘doorzet’ bij propaantanks onder de activiteit   staat. Maar… Wanneer de doorzet betrekking heeft op twee tanks, met   verschillende vulpunten (referenties), kan een verdeling van de doorzet over   de verschillende referenties gerechtvaardigd zijn. Omdat ook de doorzet   bepalend is voor de omvang van een contour (en niet op de activiteit zelf)   lijkt het mij ook beter om ‘de doorzet’ ook als kenmerk aan ‘Referentie’ te   koppelen ipv aan ‘Activiteit’.
 
Onder E9   worden kenmerken onder ‘Activiteit’ vermeld die alleen betrekking hebben op   Activiteiten met bepaalde toxische stoffen. (Daar gelden de kenmerken voor,   namelijk om de toxiciteit te bepalen). Vervolgens zijn hier dan   aandachtsgebieden (GAG) aan gekoppeld, afhankelijk of Toxische stofgroep (GT   5; LT3 en/of LT4) aanwezig is.
Ik kan   mij voorstellen dat de aan- of afwezigheid van LT3/4 en/of GT5 aan   ‘Activiteit’ wordt gekoppeld, en dan bij afwezigheid van deze stoffen of   juist bij aanwezigheid per categorie en keuze wordt gemaakt onder   ‘Referentie’ (“geen GT5/LT3/LT4; GT5; LT4; LT3)
 
Kortom:
Graag   nog eens bekijken of de locaties van kenmerken met invloed op de contour in   het IM de juiste plek hebben gekregen.

**Comment by PalmJanssen** [comment]
Tekst Antea:
Analyse/Oplossing:

Hieronder   ook nog mijn aanvullingen op het wijzigingsverzoek van Rinus de Bruijne.
--
Ik heb   met Rinus gesproken over de opbouw van het model met name over het opnemen   van de kenmerken van de activiteiten.
Deze   (extra) kenmerken zijn geïnventariseerd door Wim Makaske, deze staan in de   bijlage incl. hoe deze zijn opgenomen in het model
Het ging   in het gesprek met Rinus met name over waar bepaalde kenmerken zijn   ondergebracht.
Uitgangspunten   die nu bij het opnemen van de kenmerken hierbij zijn gehanteerd zijn globaal:
1   Kenmerken in het BKL bijlage VII zijn genoemd worden opgenomen bij deze   Activiteit (dit is de oorsprong van de groene blokjes per activiteit)
2   Kenmerken die maar voor 1 activiteit gelden niet opnemen bij de referentie   (referenties gelden namelijk voor veel meer activiteiten gelden, soms   tientallen)
3   Kenmerken die evident bij de referentie horen en gekoppeld zijn aan meerdere   activiteiten (denk hierbij aan oppervlakte of inhoud van een   OpslagReferentie) wel bij de referentie
Rinus   gaf aan dat bepaalde kenmerken die nu bij de activiteit staan beter bij de   referentie kunnen staan omdat kenmerken binnen één activiteit per referentie   kunnen verschillen.
Als   sprekend voorbeeld het kenmerk soortBlusinstallatie (kenmerk dat nu bij 1   activiteit aanwezig is).
Volgens   Rinus hoort dit bij de referentie omdat er bij verschillende referenties   (opslagplaatsen) op 1 locatie verschillende blusinstallaties kunnen zijn, dit   zorgt dan ook voor een andere contour per referentie als je dit bij de   activiteit plaatst kan je maar 1 blusinstallatie registreren.
We   kunnen de plaats van de kenmerken natuurlijk heroverwegen en/of   uitgangspunten aanpassen en dan het model hierop aanpassen. De impact hiervan   is hoog omdat dan veel kenmerken verschoven moeten worden en er meer   referentiestypes moeten komen. Dit zorgt voor veel nieuwe modellen en   aanpassingen in de rest van de keten. Dit moet dus in overleg besloten   worden.
Pragmatische   oplossing is er ook (zonder aanpassingen in het model), deze noem jij ook al,   hierbij wordt dezelfde activiteit meerdere keren geleverd met de   verschillende waarden voor de betreffende kenmerken.
Of   zoals jij het beschrijft :
“Volgens   mij zit een deel van de oplossing erin dat als er bijvoorbeeld meerdere   opslagunits zijn (of tanks) dat dit wel verschillende activiteiten zijn en   dus als aparte activiteit in het REV worden ingevoerd, al staan ze op   dezelfde locatie. Vroeger keek men per inrichting, maar onder de Omgevingswet   kijkt men per activiteit”
Dit kan   ook nog meegenomen worden in de besluitvorming

**Comment by PB-GNM** [comment]
Wie is "ik"?

**Comment by PB-GNM** [comment]
nr in eerste issuelijst: 1

**Comment by BrittvanWaveren** [comment]
Beste Paul, hierbij zoals verzocht de reactie van Geodan:

Technische impact: Oplossing 2 heeft ook onze voorkeur. Oplossing 2 heeft geen impact op de REV API. De REV API specificatie hoeft hiervoor niet gewijzigd te worden. Het REV checkt niet of op eenzelfde locatie eenzelfde activiteit meerdere keren voorkomt, technisch is dat derhalve dus toegestaan.

**Comment by PalmJanssen** [comment]
Deze tekst opgenomen in het IMEV document:

OPMERKING: Het kan voorkomen dat er binnen een locatie meerdere EVActiviteiten worden uitgevoerd. Er zijn dan vanuit één locatie meerdere verwijzingen naar verschillende EVActiviteiten. Het kan ook zijn dat er binnen één locatie binnen één EVActiviteit meerdere specifieke voorkomens van die EVActiviteit nodig zijn. Bijvoorbeeld als er verschillende typen blusinstallaties zijn gespecificeerd. Ook in dat geval is er een koppeling met meerdere voorkomens van EVActiveit.
