### ISSUE TITLE
Verplichte Character string

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#3]
nr in eerste issuelijst: 2
Indiener:  Nick Naus GEODAN

**Vraag:**
Onze ontwikkelaars vragen zich af wat de definitie van 'verplicht' betekent. Het invullen van een 'spatie' is nu volgens het model voldoende om aan de verplichting te voldoen. Zijn er algemene regels die we kunnen gebruiken om het verplicht invullen van tekstvelden goed te checken? Kunnen deze opgenomen worden in het model?

**Antwoord:**
Waarmee de CharacterStrings worden gevuld is in het IMEV niet beschreven. Wel moeten ze voldoen aan de beschrijving die is gegeven in het woordenboek.

**Comment by PalmJanssen** [comment]
Het is welliswaar logisch dat een characterstring betekenisvol wordt ingevuld maar er kan een ontstaan dat spaties of tabs gebruikt worden om aan te geven dat een veld leeg is. Deze escape is niet zinvol en niet de bedoeling. Validatie hierop kan zinvol zijn. Om dit te kunnen doen is het nodig om in de IMEV standaard daar iets over op te nemen.

**Comment by PalmJanssen** [comment]
De volgende tekst is in de standaard gezet:

10.1.2 attributen van tekstvelden

De inhoud van de waarden bij attributen met een tekstveld bevat een betekenisvolle tekenreeks (character string). Een leesteken als bijvoorbeeld een spatie, tab of vergelijkbaar mag niet gebruikt worden om aan te geven dat een attribuut is ingevuld maar geen waarde heeft.

**Comment by BrittvanWaveren** [comment]
Beste Paul, hierbij zoals verzocht de reactie van Geodan:

Technische impact: het heeft onze voorkeur om een regular expression op te nemen bij de verplichte attributen van het type CharacterString. In de regular expression kan bijv. opgenomen worden dat er minimaal een letter en/of cijfer in de waarde moet voorkomen. Ditzelfde kan toegepast worden bij optionele velden. Dan moet de waarde leeg zijn of voldoen aan de regular expression. Geonovum/Werkgroep mag met een voorstel komen wat er in de regular expression opgenomen moet worden.
