### ISSUE TITLE
Klopt de definitie bij de omschrijving van de Seveso­Referentie wel?

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#30]
![image](https://user-images.githubusercontent.com/80040145/144080891-a796a8dd-a043-4342-b8b7-07e1d73b6e1c.png)

**Comment by PB-GNM** [comment]
Waarom staat het woord "geometrische" er in?
Is het misschien een kopieerfoutje uit de geometrie?

**Comment by PalmJanssen** [comment]
Voorstel: Definitie omschrijving aanpassen naar "Beschrijving in woorden van de betreffende SevesoReferentie"

**Comment by PalmJanssen** [comment]
Conclusie werkgroep: pas aan.

**Comment by PB-GNM** [comment]
Gesloten, omdat het verwerkt is in versie 1.2 en omdat die versie goedgekeurd is.
