### ISSUE TITLE
Verzoek tot opnemen constraints (SDIMEV-37, Welt 215)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#33]
Janne Verstappen merkt op dat er op dit moment geen constraints in IMEV staan zoals min en max waarde of aantallen getallen achter de komma.
Die zullen dus nog geïnventariseerd moeten worden en verwerkt in het model.

Ook moet daarna nog uitgezocht worden hoe die vervolgens in het Json schema terecht komen.

Bijvoorbeeld het attribuut vermogen bij Windturbine.
Dat heeft nu kW als eenheid en Real als type. Kan dus zijn 1 maar ook 1,2 of 1,2344 etc
https://docs.geostandaarden.nl/imev/imev/#detail_attribute_IMEVBasis_Windturbine_vermogen

**Comment by PalmJanssen** [comment]
Voor 1.2 kunnen we denk ik beginnen met de opname van een aantal bekende constraints. Dan is het format en aanpak duidelijk.
Belangrijke model constraints die er nu niet instaan zijn ... nog afmaken

**Comment by PB-GNM** [comment]
In Enterprise Architect is dit wel aan te geven bij attributen. Hieronder een voorbeeld uit IMgeluid:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/80040145/153216842-a50efcf7-f34f-4996-b3a2-860854020820.png">

**Comment by PalmJanssen** [comment]
In MIM is dit nog niet anders gestandaardiseerd dan met een constraint.
Er is een MIM wijzigingsvoorstel hiervoor: https://github.com/Geonovum/MIM-Werkomgeving/issues/109
Indien dit nodig is, dat voorstel volgen

**Comment by PalmJanssen** [comment]
## Aanleiding wijziging
In IMEV staat bij numerieke waarden alleen aangegeven of de waarde een Integer (geheel getal) of een Real (decimaal getal) is. Er staan geen andere invulvoorschriften (of constraints) voor numerieke waarden. Zoals bijvoorbeeld minimumwaarde, maximumwaarde, aantal cijfers achter de komma. Er kan dus op dit moment niet gevalideerd worden op deze invulvoorschriften.

## Voorgestelde wijziging
Neem bij de kenmerken waar dat nodig is invulvoorschriften op in de vorm van constraints als minimum, maximum, aantal decimalen etc.

Er zijn zo'n 6 integer en 40 real waarden in IMEV. Ze komen voor bij typische kenmerken als afstand, oppervlakte, inhoud, aantal, lengte, massa etc.

## Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? **dataprovider, REV, Softwareleveranciers**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
- Heeft het impact op het json-schema? **Nog niet bekend. Waarschijnlijk niet. De invulvoorschriften kunnen met validatieregels gecontroleerd worden**

## Prioriteit
**laag**

## Toelichting
Er zijn zo'n 6 integer en 40 real waarden in IMEV. Ze komen voor bij typische kenmerken als afstand, oppervlakte, inhoud, aantal, lengte, massa etc.
Er zijn een aantal aspecten:
- tot nu toe heeft gebrek deze specificaties en validatie daarop nog weinig problemen opgeleverd. Tenminste er is hier niets over bekend.
- in de omzetting naar REV worden waarden omgezet zoals ze zijn. Zijn daar invulvoorschriften toegepast?
- het is relatief veel werk om voor alle kenmerken met een numerieke waarde dit te specificeren en in software af te dwingen.

**Comment by PB-GNM** [comment]
Wat levert het op: datakwaliteit.
geen harde noodzaak, maar wel wenselijk.
Vooral de eenheden zijn belangrijk.
Voorstel: niet voor komende versie maar voorbereide3n voor volgende, want inventarisatie door experts is nodig.

**Comment by PB-GNM** [comment]
Adviesgroep 13-9-2023 heeft besloten deze wijziging nog niet door te voeren voor versie 2.0.
Eerst moet de bovengenoemde inventarisatie uitgevoerd worden.

**Comment by PB-GNM** [comment]
Hieronder staat een voorstel t.a.v. de lengte, minimale waarde en maximale waarde voor alle numerieke attributen:

|klasse|attribuut|type|lengte|meeteenheid|voorstel min|voorstel max|min gemeten|max gemeten|missing value %|
|------|---------|-----------|-----------|------------|------------|-----------|-----------|---------------|
|TankenCNG|aantalAutobussen|Integer|3,0|aantal|0|999|8|101|99,92||
||TankenCNG|aantalPersonenauto|Integer|3,0|aantal|0|999|10|300|99,91|
|Machinekamer|aantalKoelinstallaties|Integer|3,0|aantal|0|999|leeg|leeg|100,00|
|AfstandOfGeometrieAandachtsgebied of Prcontour|afstand|Real|4,2|m|0|9999,99|0|1500|0,36|
|BuisleidingReferentie|bovenkantbuis|Real|4,0|cm|-9999|9999|-1443|2485|75,26|
|BuisleidingReferentie|maximaleWerkdruk|Real|5,0|kPa|0|99999|0|99999|24,12|
|BuisleidingReferentie|wanddikte|Real|4,2|mm|0|9999,99|0|9999,99||
|BuisleidingReferentie|diameter|Real|4,2|mm|0|9999,99|0|9999,99||
|Leiding|diameter|Real|4,2|mm|0|9999,99|0|9999|17,70|
|OpslagSevesoHoeveelheidBuitenSevesoInrichting|dampspanning|Real|7,2|mbar|0|9999999,99|leeg|leeg|100,00|
|OpslagtankPropaanPropeen_VasteAfstandVergunningplicht|doorzetPerJaar|Real|7,2|m3|0|9999999,99|12|2000000|15,06|
|TankenLPG|doorzetPerJaar|Real|7,2|m3|0|10000,00|249|2500|6,65|
|OpslagVuurwerkF1F2F3T1T2 of F4|hoeveelheidVuurwerk|Real|7,2|kg|0|1000000,00|50|166000|54,35|
|OpslagSevesoHoeveelheidBuitenSevesoInrichting|kookTemperatuur|Real|7,2|Kelvin|0|9999999,99|leeg|leeg|100,00|
|OpslagSevesoHoeveelheidBuitenSevesoInrichting|kritischeTemperatuur|Real|7,2|Kelvin|0|9999999,99|leeg|leeg|100,00|
|OpslagSevesoHoeveelheidBuitenSevesoInrichting|mediaanLetaleConcentratie|Real|7,2|ppm|0|9999999,99|leeg|leeg|100,00|
|OpslagOntplofbaarADR1.1Civiel|nettoExplosieveMassa|Real|7,2|kg|0|10000,00|2|1500||
|OpslagOntplofbaarADR1.3Civiel|nettoExplosieveMassa|Real|7,2|kg|0|10000,00|37|700||
|BehandelenRegelenMetenAardgas_VasteAfstandGeenVergunningplicht|ontwerpCapaciteit|Real|7,2|Nm3/u|0|1000000,00|4000|87000|9,48|
|AmmoniakKoelinstallatie_TeBerekenenAfstand|werktemperatuur|Real|7,2|Celsius|-273|100,00|-26|-5|37,50|
|AmmoniakKoelinstallatie_VasteAfstandVergunningplicht|werktemperatuur|Real|7,2|Celsius|-273|100,00|-47|-4|22,62|
|BehandelenRegelenMetenAardgas_VasteAfstandGeenVergunningplicht|werkdruk|Real|5,0|kPa|0|99999|800|10000||
|Windturbine_TeBerekenenAfstandGeenVergunningplicht|aantalWindturbines|Integer|3,0|aantal|0|999|1|2|0,00|
|Windturbine_TeBerekenenAfstandVergunningplicht|aantalWindturbines|Integer|3,0|aantal|0|999|1|93|0,00|
|Windturbine|ashoogte|Real|7,2|m|0|1000,00|3,9|166|15,49|
|Windturbine|breedteGondel|Real|7,2|m|0|100,00|1,21|1,21|99,97|
|Windturbine|hoogteGondel|Real|7,2|m|0|100,00|1,18|1,18|99,97|
|Windturbine|lengteGondel|Real|7,2|m|0|100,00|2,32|2,32|99,97|
|Windturbine|massaGondel|Real|7,2|kg|0|10000,00|200|2000|99,95|
|Windturbine|maxWerpafstandNominaal|Real|7,2|m|0|1000,00|16|454|27,33|
|Windturbine|maxWerpafstandOvertoeren|Real|7,2|m|0|1000,00|102|716|27,82|
|Windturbine|nominaalToerental|Real|7,2|Hz|0|1000,00|4,8|175|99,92|
|Bewaarplaats|oppervlakteDeuropening|Real|1,0|m2|0|100|1|8|98,63|
|Windturbine|rotordiameter|Real|7,2|cm|0|12000,00|3,7|12000|15,51|
|Windturbine|vermogen|Real|7,2|KW|0|100000,00|5|12000|20,38|
|Windturbine|zwaartepunt|Real|7,2|m|0|1000,00|2,77|2,77|99,97|
|OpslagReferentie|inhoud|Real|5,0|m3|0|99999|0|36000|61,45|
|OpslagReferentie|oppervlakte|Real|4,0|m2|0|9999|2|2501|99,15|
|BevoorradingCategorieOfExactAantal|exactAantal|Integer|4,0|aantal|0|9999|0|5000|0,11|
|ReactietijdNoodstopBooleanOfExact|exactAantalSeconden|Integer|4,0|aantal|0|9999|0|9999|99,99|
|VoordrukBooleanOfExact|exacteHoeveelheid_kpa|Real|5,0|kPa|0|99999|0|99999|99,99|
|KwetsbaarGebouw|populatie|Real|6,0|aantal|0|999999|0|999999|100,00|
|KwetsbareLocatie|populatie|Real|6,0|aantal|0|999999|0|999999|100,00|

Het verzoek is aan alle domeinexperts om deze voorgestelde waarden te beoordelen en hieronder eventueel betere voorstellen te doen.

**Comment by PB-GNM** [comment]
Hieronder staat een voorstel t.a.v. de patronen voor alle string-attributen voorzover ze niet volledig vrij zouden moeten zijn en voorzover ze niet al opgenomen zijn:
|klasse|attribuut|voorgesteld patroon|voorgesteld formeel patroon|bevinding in REV|
|------|---------|-------------------|---------------------------|----------------|
|BKLActiviteit|basisVergunningNummer|Vrij in te vullen veld tot 50 karakters.|.{1,50}|nummer en/of  strings tot 44 karakters komen voor|
|ExterneVeiligheidsObject|bronobjectID|Vrij in te vullen veld tot 50 karakters.|.{1,50}|komt nog niet voor|
|KwetsbaarGebouw|kadastraleAanduiding|"Combinatie van de volgende subdomeinen:
KadastraleGemeentecode: een code waarmee een kadastrale gemeente wordt geïdentificeerd.
Formaat AN5 (AAANN).
KadastraleSectie: een code waarmee een deel van een kadastrale gemeente wordt geïdentificeerd.
Formaat AN...2.
KadastraalPerceelnummer: de nummering van een kadastraal perceel. 
Formaat N...5.
KadastraleOnroerendeZaakIndexLetter: een code waarmee het type kadastrale onroerende zaak wordt aangegeven. 
Domein: A: appartement; B: beklemobject; D: deelperceel; G: geheel perceel. Formaat AN1.
KadastraleOnroerendeZaakIndexNummer: een unieke aanduiding binnen het kadastraal peceel. 
Bij index letter G komt alleen nummer ""0000"" voor. 
Bij index letter B en D komen nummers ""0001""- ""9999"" voor. 
Bij index letter A komen nummers ""0000""- ""9999"" voor. Domein 0000 - 9999. Formaat N4."|[A-Z]{3}\d{2}[A-I,K-Z]{1,2}\d{5}[G][0]{4}|([A,B,D]\d{4})||
|KwetsbareLocatie|kadastraleAanduiding|"Combinatie van de volgende subdomeinen:
KadastraleGemeentecode: een code waarmee een kadastrale gemeente wordt geïdentificeerd.
Formaat AN5 (AAANN).
KadastraleSectie: een code waarmee een deel van een kadastrale gemeente wordt geïdentificeerd.
Formaat AN...2.
KadastraalPerceelnummer: de nummering van een kadastraal perceel. 
Formaat N...5.
KadastraleOnroerendeZaakIndexLetter: een code waarmee het type kadastrale onroerende zaak wordt aangegeven. 
Domein: A: appartement; B: beklemobject; D: deelperceel; G: geheel perceel. Formaat AN1.
KadastraleOnroerendeZaakIndexNummer: een unieke aanduiding binnen het kadastraal peceel. 
Bij index letter G komt alleen nummer ""0000"" voor. 
Bij index letter B en D komen nummers ""0001""- ""9999"" voor. 
Bij index letter A komen nummers ""0000""- ""9999"" voor. Domein 0000 - 9999. Formaat N4."|[A-Z]{3}\d{2}[A-I,K-Z]{1,2}\d{5}[G][0]{4}|([A,B,D]\d{4})||
|Documentatie|link|Liefst beginnend met https en maximaal 2048 omdat veel browsers langer niet aan kunnen|.{1,2048}|lengte 700 komt voor in REV en 2048 is maximale lengte in Chrome en Explorer|
|SpoorVervoer|trajectcode|Minimaal 2 cijfers en maximaal 3|[0-9]{2,3}||
|WaterVervoer|watervakcode|Minimaal 1 hoofdletter en maximaal 4|[A-Z]{1,4}||
|WegVervoer|wegvakcode|Vrij in te vullen veld min 2 karakters maximaal 8 en altijd beginnend met 1 hoofdletter|[A-Z]{1}.{1,7}|O43/O118 is de langst ingevulde|

**Comment by JanCasSmitGeonovum** [comment]
zie document aanpassingen 2.1
[aanpassingen 2.1.xlsx](https://github.com/user-attachments/files/16053601/aanpassingen.2.1.xlsx)

**Comment by PB-GNM** [comment]
n.a.v. de buisleidingexpert bijeenkomst van 8 juli is het patroon van wanddikte van 4,0 naar 4,2 gezet, omdat in de praktijk wanddiktes ook met 2 cijfers achter de komma in mm worden opgegeven.
