### ISSUE TITLE
Nalopen van datatypen op inconsequenties en juistheid (SDIMEV-38)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#34]
Janne Verstappen merkt op dat de gegevens types niet consequent zijn voor ‘Reals’ en ‘Integers’. Voorbeeld: Leiding|diameter|integer vs buisleidingreferentie|diameter|real. Maar ook van bv ‘aantalAutobussen’(per etmaal) is het de vraag of dit een integer moet zijn, en als dat zo is, hoe er afgerond moet worden op gehele getallen.

Het verzoek is om het hele model hierop na te lopen.

**Comment by PB-GNM** [comment]
<img width="122" alt="image" src="https://user-images.githubusercontent.com/80040145/153218789-14361b62-e240-43e1-824a-eae523d07f67.png">
<img width="233" alt="image" src="https://user-images.githubusercontent.com/80040145/153218967-6e5834e0-c498-4a32-bee8-65cce0d30692.png">

**Comment by PalmJanssen** [comment]
Werkgroep: haal de inconsequenties weg. In dit geval beide Real

**Comment by PalmJanssen** [comment]
heel veel maatvoeringen staan in integer. Ik zou real verwachten. Allemaal omzetten?

- oppervlakteDeuropening
- hoeveelheidVuurwerk
- ontwerpCapaciteit
- werkdruk

**Comment by PalmJanssen** [comment]
- doen

**Comment by PB-GNM** [comment]
Gesloten, omdat het verwerkt is in versie 1.2 en omdat die versie goedgekeurd is.
