### ISSUE TITLE
Inbouwen van keuzes (SDIMEV-39)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#35]
Janne Verstappen meldt het volgende: 

"Een validatieregel die we niet terug zien in het model is bij aandachtsgebieden: bronhouder moet een afstand OF een geometrie opgeven. Kan dit in het model worden verwerkt?
Toelichting:
Dit is verplicht en een logische XOR 
in OpenAPI termen een oneOf, bijvoorbeeld door het invoegen van een ander attribuut: 
bv. zone, als volgt
schema.components:
GifwolkAandachtsgebied:
required:
•	zone
properties:
zone:
etc
zone:
oneOf:
•	$ref: ‘#/Afstand’
•	$ref: ‘#/Geometrie’"
– 

Onderzocht moet worden of dit met de "choice" optie in EA kan. De vraag is dan hoe het vervolgens in de json-schema's terecht zal komen.

**Comment by PB-GNM** [comment]
https://github.com/Imvertor/Imvertor-Maven/issues/172 beschrijft hoe het in Imvertor opgelost wordt.

**Comment by PalmJanssen** [comment]
Kan met een MIM Keuze modelelement of met een OCL constraint.

Wie geeft aan waar die choice moet komen? Graag een lijst.

**Comment by PalmJanssen** [comment]
De keuze tussen afstand of geometrie is bij de PRContour:
![image](https://user-images.githubusercontent.com/9932784/153223404-29bded4b-fac3-4e0d-9e6a-2fafc052e4f4.png)

**Comment by PalmJanssen** [comment]
Dit kan op twee manieren:
1) met een formele constraint: Voordeel, verandert niets aan model maar formaliseert semantiek en validatieregel
![image](https://user-images.githubusercontent.com/9932784/153226824-c75ccfc5-24bf-4226-92dd-c16023b1c998.png)

2) met een model keuze element: voordeel, implementatie in JSON kan automatisch (?)
![image](https://user-images.githubusercontent.com/9932784/153228889-da5b5948-2212-4ac8-9462-a69d28ab5bf6.png)

**Comment by PalmJanssen** [comment]
Werkgroep:
- maak een keuze uit optie 1 en optie 2.
- liefst optie 2 (omdat we dat overal doen) maar kijk wat de bezwaren zijn
- vraag aan Geodan

**Comment by PalmJanssen** [comment]
optie 2 is gekozen

**Comment by PB-GNM** [comment]
Gesloten, omdat het verwerkt is in versie 1.2 en omdat die versie goedgekeurd is.
