### ISSUE TITLE
Geometrietypen gebruiken zoals gebruikelijk voor GeoJSON (SDIMEV-40)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#36]
Objecten als VlakOfLijn zijn in het model geïmplementeerd met dingen als GM_Polygon en GM_Line. Dit lijkt op GML, maar in JSON zou je hier wellicht GeoJSON implementatie moeten gebruiken conform de beschrijving van het Geometry Object? https://datatracker.ietf.org/doc/html/rfc7946#page-7

**Comment by PalmJanssen** [comment]
In het UML worden conceptuele geometrietypen gebruikt uit ISO 19107 Spatial Schema. GM_ staat voor geometry model. Niet voor GM...L. GML heeft daar implementaties van, die kom je dan tegen in een GML schema of GML bestand. GeoJSON heeft daar ook implementaties van, die kom je dan tegen in het JSON schema en bestand.

conclusie geen aanpassing nodig. UML blijft implementatievrij.

**Comment by PB-GNM** [comment]
klopt. Bij het wegschrijven van het json-schema in yaml-format vanuit IMEV worden Geojson geometrie schema's opgenomen:
<img width="140" alt="image" src="https://user-images.githubusercontent.com/80040145/153222455-44e7fb3b-93b1-4b9c-8e28-16f0997f7484.png">

**Comment by PalmJanssen** [comment]
Werkgroep:
ok

**Comment by PB-GNM** [comment]
Gesloten, omdat het een "wontfix" label heeft.
