### ISSUE TITLE
waardelijst soortblusinstallaties, niet compleet?

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/imev-werkomgeving#37]
Onderstaand de huidige inhoud van de waardelijst soortblusinstallaties V1.0.
Daaronder de lijst zoals in BKL, bijlage VII tabel B.3.
Vraagt dat om een uitbreiding van de waarden in de IMEV lijst?

![image](https://user-images.githubusercontent.com/9932784/146761924-4cf7ee1a-d104-4d60-a06c-dfe0e299f403.png)

 
Informatie over blusinstallaties uit BKL VII tabel B.3

**Beschermingsniveau volgens PGS 15, blussysteem en stikstofgehalte** 

**Beschermingsniveau 1** 
(Semi-)automatische monitorinstallatie 
Automatische deluge installatie 
Automatische hi-ex outside-air installatie, stikstofgehalte < 5%
Automatische hi-ex outside-air installatie, stikstofgehalte 5 ≤ 10%
Automatische hi-ex outside-air installatie, stikstofgehalte > 10% 
Bedrijfsbrandweer met ter plaatse blussen, stikstofgehalte < 5% 
Bedrijfsbrandweer met ter plaatse blussen, stikstofgehalte 5 ≤ 10% 
Bedrijfsbrandweer met ter plaatse blussen, stikstofgehalte > 10% 

**Beschermingsniveau 2a, stikstofgehalte < 5 %** 
ADR-klasse 3 in kunststof 
ADR-klasse 3 niet in kunststof 
Geen ADR-klasse 3

**Beschermingsniveau 2a, stikstofgehalte 5 ≤ 10%**
ADR-klasse 3 in kunststof
ADR-klasse 3 niet in kunststof 
Geen ADR-klasse 3

**Beschermingsniveau 2a, stikstofgehalte > 10 %**
ADR-klasse 3 in kunststof 
ADR-klasse 3 niet in kunststof 
Geen ADR-klasse 3 

**Beschermingsniveau 3**
Stikstofgehalte < 5%
Stikstofgehalte 5 ≤ 10% 
Stikstofgehalte > 10%

**Alle beschermingsniveaus** 
 Gasflessen

**Comment by PalmJanssen** [comment]
reactie Manuel Betermans (RWS)
Ik ben het met jullie eens dat de lijst in de tabel van het Bkl en die uit het IMEV overeen zouden moeten komen; mij is niet bekend waarom hier een verschil in zou moeten zitten. Een tijd geleden hebben Hans de Waal en Wim Makaske (nu niet meer bij ministerie en bij ons werkzaam) een inventarisatie gemaakt van kenmerken die in de IMEV’s moesten. Op pagina 5 hebben ze dit voor tabel B3 gedaan, maar daar mis ik bijvoorbeeld in hun opsomming ook een Automatische hi-ex outside-air installatie; mij is niet duidelijk waarom dat zo is. Ik zou dus toch tabel B3 en de aanvullingen die Paul heeft gedaan als uitgangspunt nemen. 
Wat uit dit document wel naar voren komt, is dat bijvoorbeeld een veld als ‘Oppervlakte opslagplaats in m2’ ook in het IMEV terug zou moeten komen. De uiteindelijk afstand uit tabel B3 hangt namelijk ook mede daarvan af; daarom is ook het beschermingsniveau als extra kenmerk voorgesteld (zie issue Opname Beschermingsniveau #18).

zie ook [doc](https://stichtinggeonovum.sharepoint.com/:w:/r/sites/msteams_4c2e57/Gedeelde%20documenten/General/5%20Werkdossier/wijzigingsvoorstellen/blusinstallaties/einddocument%202020%20REV%20-%20Kenmerken%20van%20activiteiten%20Bkl%2010.3%20f%20en%20g.docx?d=wd1e03ea05dcf412e80e9470605cd9c42&csf=1&web=1&e=ybn3Pw):

**Comment by PalmJanssen** [comment]
Werkgroep:
- wat is de argumentatie achter keuze van de huidige waarden in de waardelijst
- alleen die (11) opnemen waar niet te berekenen achterstaat (tabel B3, Bkl) blz 264, bijlage VII
- kom met voorstel

**Comment by PalmJanssen** [comment]
dit is het voorstel:

was:
![image](https://user-images.githubusercontent.com/9932784/155350837-d0bf0f36-1f91-4497-94bf-af0b7bd33ca5.png)

wordt:
![image](https://user-images.githubusercontent.com/9932784/155351157-b8ffa148-57be-40e3-aac7-e47a9741933b.png)

**Comment by PB-GNM** [comment]
Klopt het dat het er 12 zijn en niet 11 zoals eerder in dit issue genoemd?

**Comment by PB-GNM** [comment]
er is een relatie met #18

**Comment by PalmJanssen** [comment]
Werkgroep.

Bekijk dit opnieuw.
- Wat is de bedoeling van dit attribuut? Je wilt weten op welke waarde uit tabel B3 de afstand is gebaseerd.
- In feite is dat de eerste kolom van de tabel.
- In die tabel zit structuur. Dat is nu vertaald naar meerdere attributen
- voorstel: kijk of je een enumeratie kan maken waar die structuur in zit. Voorstel naam van de enumeratie. ..... Tabel B3.....

**Comment by PalmJanssen** [comment]
Voorstel voor enumeratie waar de inhoud van tabel b3 in is verwerkt.

![image](https://user-images.githubusercontent.com/9932784/157272555-9700c806-6f2a-4b34-8256-c704a3e3e84a.png)

**Comment by PalmJanssen** [comment]
Bericht Boudewijn:
Naar de mening van Rogier en mijzelf is het niet nodig of gewenst om - naast de nieuwe tabel - andere attributen te behouden. Stikstofgehalte, ADR in kunststof verpakking, etc. zijn alleen relevant bij bepaalde systemen en uit de nieuwe tabel blijkt duidelijk wanneer een specifiek aspect relevant is.
Dus alleen de enumeratie van de nieuwe tabel (BeschermingsniveauTabelB3) en daarnaast de 'oppervlakte' zijn relevant voor de aan te houden vaste 'afstand'.
De andere attributen (SoortBlusinstallatie, CategorieStikstofgehalte, OpslagADRklasse3, opslagGasflessen) kunnen dus worden verwijderd.

**Comment by PalmJanssen** [comment]
Verwerking:

![image](https://user-images.githubusercontent.com/9932784/158181782-72464046-c5c3-4fd9-a70d-24ff4c7aec0f.png)

**Comment by PB-GNM** [comment]
Gesloten, omdat het verwerkt is in versie 1.2 en omdat die versie goedgekeurd is.
