### ISSUE TITLE
SDIMEV-41: REV-helpdesk 22 01 2718: invullen getal aantalBevoorradingen als enumeratie

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#39]
Dit is een wijzigingsverzoek uit de REV-helpdesk (22 01 2718 ) die als volgt is omschreven "*invullen getal aantalBevoorradingen (A7: OpslagPropaanPropeen_VasteAfstandGeenVergunningplicht) aanpassen naar categorie (enumeratie)*"

**Comment by PB-GNM** [comment]
Welke waarden mogen er dan in de enumeratie?

**Comment by manuelbeterams** [comment]
Voor het aantal bevoorradingen staan in het Bal tabel 4.899 twee opties, 5 of minder bevoorradingen of meer dan 5.

**Comment by PalmJanssen** [comment]
Werkgroep:
Bal tabel 4.899.
Noemt twee categorien <= 5 en > 5.
Het is de vraag of we liever de indiener een schatting laten maken of dat we de indiener een categorie laten invullen. (actie Peter)

De Opslag inhoud wordt ook in Tabel 4.899  genoemd maar zit bij ReferentieEVContour bij OpslagReferentie.inhoud

**Comment by PB-GNM** [comment]
Inmiddels is Peter vervangen door Frans Geurts. 
Frans geeft aan dat het vooral gewenst is omdat er dan minder fouten gemaakt kunnen worden door de indieners.
Er is een relatie met #40.

**Comment by PB-GNM** [comment]
Het oplossingsvoorstel is om de enumeratie in te voeren.

**Comment by PB-GNM** [comment]
## Aanleiding wijziging
De aanleiding is dat er minder fouten worden gemaakt wanneer er categorieën gebruikt worden.

## Voorgestelde wijziging

Het voorstel is om op de plek waar nu "Integer" staat de enumeratie CategorieAantalBevoorradingen, en dat verwijst dan naar een enumeratie met de 2 waarden "<= 5" en "> 5".

<img width="211" alt="image" src="https://user-images.githubusercontent.com/80040145/153229906-93adc507-34ba-4fd5-b107-df93a0f9a83c.png">

## Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? **dataprovider en gebruiker REV en Softwareleveranciers**
- Verandert de semantiek van de standaard? **Nee**
- Heeft het impact op het json-schema? **Ja**

## Prioriteit
Middel

## Toelichting
Er is een relatie met #71.

**Comment by PB-GNM** [comment]
Aandachtspunt. Er is een extra conversie nodig en dat is een risico.
nieuw voorstel: keuze object: categorie of exact aantal

**Comment by PB-GNM** [comment]
Opgelost in versie 1.3.
