### ISSUE TITLE
bronhouder code in plaats van bronhouder (naam)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#4]
nr in eerste issuelijst: 3
Indiener: Nick Ron Arno

ik heb samen met Arno en Ron enkele functionele vragen en de daarbij horende technische oplossingen verder uitgewerkt voor het kunnen faciliteren van het splitsen en fuseren van bronhouders in het REV. Om dit mogelijk te maken is ook een kleine aanpassing aan het IMEV nodig. We willen graag het attribuut 'bronhouder' laten wijzigen naar 'bronhoudercode' en dit veld verplicht maken. Dit zodat we het kunnen gebruiken om voor autorisatiedoeleinden en omdat het zo voor de eindgebruiker snel te zien wie de bronhouder is. 

**Analyase/Oplossing**
Bronhouder CODE als verplicht veld toevoegen aan ExterneVeilgheidsObject, bronhouder (naam) blijft als optioneel veld ook aanwezig

**Comment by PalmJanssen** [comment]
Dit is al verwerkt in de overgedragen versie.

**Comment by BrittvanWaveren** [comment]
Beste Paul, hierbij zoals verzocht de reactie van Geodan:

Bij het fuseren of splitsen geven we nu in de metadata van het document in de database aan welke bronhouder eigenaar is/wordt van het document. Voor het fuseren of splitsen hoeven we daarom zelf geen wijziging aan te brengen in de bronhoudercode in het ExterneVeiligheidsObject. Wij vinden het ook niet gewenst als wij bij het fuseren of splitsen van bronhouders documenten moeten aanpassen, daarom passen we alleen de eigenaar aan in de metadata van het document.
Voor gebruikers is het wel handig om via de bronhoudercode in het ExterneVeiligheidsObject te zien welke bronhouder eigenaar is van een document.

Technische impact van de voorgestelde wijziging: We moeten de REV API specificatie updaten.
Om te voorkomen dat wij bij een fusie of splitsing alsnog zelf de documenten moeten bewerken (bronhouder en bronhoudercode in het ExterneVeiligheidsObject updaten naar de nieuwe bronhouder) kan een procesafspraak gemaakt worden dat bronhouders zelf de data moeten wijzigen (middels een aanlevering aan het REV).
