### ISSUE TITLE
SDIMEV-41: REV-helpdesk 22 01 2717: invullen getal voor doorzetPerJaar  als enumeratie

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#40]
Dit is een wijzigingsverzoek uit de REV-helpdesk (22 01 2717 ) die als volgt is omschreven "*invullen getal voor doorzetPerJaar (A1a: TankenLPG) aanpassen naar categorie (enumeratie);*"

**Comment by manuelbeterams** [comment]
De afstanden die voor deze activiteit gelden hangen af van de doorzet. Die doorzet valt uiteen in drie categorieën: minder dan 500 m3, tussen 500 en 1000 m3 en meer dan 1000  m3. Voorstel is om die drie categorieën toe te voegen in plaats van een exact getal voor doorzet

**Comment by PalmJanssen** [comment]
zie ook #39 

Het is de vraag of we liever de indiener een schatting laten maken of dat we de indiener een categorie laten invullen. (actie Peter)

**Comment by PB-GNM** [comment]
Inmiddels is Peter vervangen door Frans Geurts. 
Frans geeft aan dat het vooral gewenst is omdat er dan minder fouten gemaakt kunnen worden door de indieners.

Bijzonder is dat er al een doorzetCategorie is, maar dat die niet meer gebruikt wordt in het model.

**Comment by PB-GNM** [comment]
De doorzetPerJaar komt ook voor bij VII-B.2: Opslagtank­Propeen_Vaste­Afstand­Vergunningplicht
Kan die gebruik maken van dezelfde categorieën?

**Comment by PB-GNM** [comment]
Het oplossingsvoorstel is om de enumeratie in te voeren voor TankenLPG en Opslagtank­Propeen_Vaste­Afstand­Vergunningplicht.
De impact is wel groter dan bij #39, omdat deze al opgenomen zijn in het REV.

**Comment by PB-GNM** [comment]
## Aanleiding wijziging
De aanleiding is dat er minder fouten worden gemaakt wanneer er categorieën gebruikt worden.

## Voorgestelde wijziging
Het voorstel is om op de plek waar nu Real staat de enumeratie CategorieDoorzetPerJaar te gebruiken.

<img width="192" alt="image" src="https://user-images.githubusercontent.com/80040145/153230462-f53def27-a92c-4d4b-b2d2-cc33a27d6576.png">

## Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? **dataprovider en gebruiker REV en Softwareleveranciers**
- Verandert de semantiek van de standaard? **Nee**
- Heeft het impact op het json-schema? **Ja**

## Prioriteit
Middel

## Toelichting
Er is een relatie met #72.

**Comment by PB-GNM** [comment]
Aandachtspunt. Er is een extra conversie nodig en dat is een risico.
nieuw voorstel: keuze object: categorie of exact getal

**Comment by PB-GNM** [comment]
De expertgroep adviseert om het toevoegen van een enumeratie voor 'doorzetperjaar' (3 categorieen) bij VII-A1a, naast de mogelijkheid voor het invullen van een getal, nog niet mee te nemen, omdat categorieen voor de 'doorzetperjaar' binnenkort mogelijk worden aangepast.

**Comment by geurtsf** [comment]
De doorzetten met bijbehorende nieuwe aan te houden afstanden zijn nog niet bekend. Althans bij mij niet. Ik zou deze wijziging nog even uitstellen tot er meer duidelijkheid is.

**Comment by PB-GNM** [comment]
In de expertgroep van 17 mei is besloten om te adviseren om te wachten op de aanpassing op de categorieën.
Mohammed el Allouchi zal navraag doen bij de expertgroep.
Wanneer de categorieën wel duidelijk zijn is het advies om het te doen met de keuze optie voor een categorie of een waarde net als bij andere issues is gedaan. zie ook #80.

**Comment by JanCasSmitGeonovum** [comment]
Er is een uitspraak van de Raad van State geweest die volgens mij relevant is voor dit verzoek. 

![Rapport LPG stations raad van state](https://github.com/Geonovum/imev-werkomgeving/assets/127755999/eaf94be9-97bc-4b98-9ee6-c2f80c7e1299)

![Nieuwe afstanden LPG doorzet](https://github.com/Geonovum/imev-werkomgeving/assets/127755999/950bb182-5da0-47a5-b433-191fc4e70168)

**Comment by geurtsf** [comment]
Hoi Jan Cas,

Dan voor het toesturen van de uitspraak.
Deze uitspraak is al een tijdje bekend en er wordt nu door het ministerie gekeken hoe hier mee om te gaan.
Onder andere is gekeken naar de knelpunten die er ontstaan bij de bestaande LPG tankstations.

Voor het REV is door Robby aangegeven dat we op dit moment de afstanden nog zo laten als ze in de wetgeving staan.
Op een later tijdstip zullen we die hoogste waarschijnlijk batchgewijs gaan aanpassen.

Groeten,
Frans Geurts

Van: Jan Cas Smit Geonovum ***@***.***>
Verzonden: dinsdag 11 juli 2023 15:17
Aan: Geonovum/imev-werkomgeving ***@***.***>
CC: Geurts, Frans (WVL) ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Geonovum/imev-werkomgeving] SDIMEV-41: REV-helpdesk 22 01 2717: invullen getal voor doorzetPerJaar als enumeratie (Issue #40)


Er is een uitspraak van de Raad van State geweest die volgens mij relevant is voor dit verzoek.

[Rapport LPG stations raad van state]<https://user-images.githubusercontent.com/127755999/252675208-eaf94be9-97bc-4b98-9ee6-c2f80c7e1299.png>

[Nieuwe afstanden LPG doorzet]<https://user-images.githubusercontent.com/127755999/252675088-950bb182-5da0-47a5-b433-191fc4e70168.png>

**Comment by PB-GNM** [comment]
Adviesgroep 13-9-2023 heeft besloten deze wijziging niet door te voeren.
