### ISSUE TITLE
SDIMEV-41: REV-helpdesk 22 01 2716: Verplaats: optionele velden bij EVActviteit(en) zoveel mogelijk naar referentieEVContouren

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#41]
Dit is een wijzigingsverzoek uit de REV-helpdesk (22 01 2716 ) die als volgt is omschreven "*Verplaats: optionele velden bij evActviteit(en) zoveel mogelijk naar referentieEVContouren*"

**Comment by manuelbeterams** [comment]
Toevoeging Arno De Ruijter (min IenW): 
Dit is eerder besproken en niet nodig bevonden om aan te passen, maar akkoord om nogmaals als verzoek tot wijziging in te dienen. Dan wordt gelijk de onderbouwing voor het  wel/niet toevoegen onderbouwd.

Voor verdere toelichting op de vraag kan het beste contact gezocht worden met de vraagstellers: Boudewijn de Hoop: B.deHoop@ODRivierenland.nl of Rogier Wegerif: rwegerif@odmh.nl

**Comment by PB-GNM** [comment]
Dat zou leiden tot dubbele opslag, want in één EVActiviteit kunnen meerdere referetieEVContouren zitten:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/80040145/153233937-dd09157a-ed89-4e8b-a390-3ea4ad7cd157.png">

**Comment by PalmJanssen** [comment]
Werkgroep:
- leidt tot dubbele opslag
- informatie opslaan daar waar het hoort. Vooralsnog lijken de opgenomen velden op de correcte plaats te zitten. Wetgevingstekst geeft hier ook richting aan.

**Comment by PalmJanssen** [comment]
Werkgroep:
Er komt een inventarisatie van waar aanpassing echt nodig is.

**Comment by PB-GNM** [comment]
Boudewijn de Hoop stelt de vraag: Wie gaat deze inventarisatie doen?

**Comment by PB-GNM** [comment]
Het verschilt per referentie en activiteit of het zinvol is om het gegeven te verplaatsen van de EVActiviteit naar de Referentie.
Boudewijn zal een motivatie geven en een eerste inventarisatie doen.
De impact zal groot zijn op zowel de inhoud van het REV als op de API.

**Comment by PB-GNM** [comment]
## Aanleiding wijziging
De aanleiding is nog niet duidelijk.

## Voorgestelde wijziging
Het wijzigingsverzoek is om optionele velden bij evActviteit(en) zoveel mogelijk naar referentieEVContouren te verplaatsen.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/80040145/153233937-dd09157a-ed89-4e8b-a390-3ea4ad7cd157.png">

## Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? **dataprovider en gebruiker REV en Softwareleveranciers**
- Verandert de semantiek van de standaard? **Nee**
- Heeft het impact op het json-schema? **Ja, groot. Dit betekent daardoor veel werk voor software leveranciers. De data die al geconverteerd is, zal omgezet moeten worden in het REV**

## Prioriteit
Middel

## Toelichting
Bij welke EVActiviteiten en referentieEVContouren dit zinvol is, moet nog vastgesteld worden.
Aan nut van deze wijziging wordt getwijfeld omdat het tot dubbele opslag zal leiden.

**Comment by PB-GNM** [comment]
In de conversie expertgroep is dit onderwerp besproken: de expertgroep geeft aan dat deze wijziging grote impact heeft en al veel locaties (met eventueel te verplaatsen attributen) in het REV zijn opgenomen; daarom voorlopig geen prioriteit geven aan deze wijziging; indien een verplaatsing van attributen belangrijk is voor VTH-leveranciers, kan dit alsnog worden opgepakt; 

Dit issue krijgt daarom het label "won't fix"

**Comment by PB-GNM** [comment]
Lage prioriteit.
wanneer voor specifieke attributen alsnog gewenst dan kan dit in latere versies opgepakt worden

**Comment by JanCasSmitGeonovum** [comment]
Expert overleg IMEV 31 MEI 2023, thema Inhoud van het REV

Voorgestelde wijziging inhoudelijk akkoord? nee, verzoek te algemeen

1.	Wat adviseren we de adviesgroep: niet doen, REV experts moeten dit gaan inventariseren
2.	Wat is de prioriteit (laag)
3.	Klopt de beschreven impact (nee)

Moeten software leveranciers benaderd worden voor dit issue en wat is de vraag aan hun.: nog niet

**Comment by PB-GNM** [comment]
Adviesgroep 13-9-2023 heeft besloten deze wijziging niet door te voeren.
