### ISSUE TITLE
SDIMEV-41: REV-helpdesk 22 01 2715: Voeg toe: een optioneel/verplicht veld voor het bevoegd gezag

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#42]
Dit is een wijzigingsverzoek uit de REV-helpdesk (22 01 2715 ) die als volgt is omschreven "*Voeg toe: een optioneel/verplicht veld voor het bevoegd gezag*"

**Comment by manuelbeterams** [comment]
toevoeging Arno de Ruijter (min IenW): Ligt eigenlijk niet voor de hand om het gegeven toe te voegen aan de IMEV.
Het bevoegd gezag van een MBactiviteit ligt vast in de wetgeving. Dit is een  gegeven dat afgeleid kan worden obv activiteit en de geografische locatie  / adres van die activiteit. Daarnaast zou je bij elke gemeentelijke herindeling dit kenmerk ook nog moeten wijzingen. Maar opgenomen als verzoek om het door te spreken en vast te leggen waarom wel/niet

**Comment by manuelbeterams** [comment]
Als dit veld wel zou worden toegevoegd, is het de vraag waar dit aan gekoppeld zou worden. Dat moet dan ook nog bepaald worden. Bij Feature Type BKLActiviteit misschien?

**Comment by PalmJanssen** [comment]
Als bevoegd gezag een individueel gegeven is: bijvoorbeeld de Gemeente X, of Provincie Y is het bevoegd gezag voor een locatie x waar een EV Activiteit y wordt uitgevoerd dan verwacht ik dat dat bij de EVActiviteit hoort.

![image](https://user-images.githubusercontent.com/9932784/153178764-8e8289e1-7901-469c-9478-d6f8a17c073e.png)

**Comment by PalmJanssen** [comment]
Werkgroep:
- het is een algemeen gegeven. Het type bevoegd gezag is van belang. Niet de naam van het bevoegd gezag.
- het kan als verplicht veld, omdat het altijd bekend is
- is waarschijnlijk een optioneel gegeven.
- de bronhoudercode verwijst al naar de organisatie die de laatste wijziging heeft aangebracht
- het lijkt een gegeven dat mogelijk ook de REV kan aanbrengen
- drie waarden voor bevoegd gezag: Rijk, Provincie, Gemeente, InTransitie

**Comment by PalmJanssen** [comment]
Toepassing in IMEV:
![image](https://user-images.githubusercontent.com/9932784/155355530-da6ac80d-9bd8-4c4b-9f2c-fddf0cc16744.png)

**Comment by PB-GNM** [comment]
Gesloten, omdat het verwerkt is in versie 1.2 en omdat die versie goedgekeurd is.
