### ISSUE TITLE
SDIMEV-41: REV-helpdesk 22 01 2714: Enumeratie en instructie voor typePlaatsgebondenRisico aanpassen

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#43]
Dit is een wijzigingsverzoek uit de REV-helpdesk (22 01 2714 ) die als volgt is omschreven "*Pas aan: de enumeratie en instructie voor typePlaatsgebondenRisico om te kunnen filteren op afzonderlijke “vastgestelde contouren” door “vastgesteld” op te splitsen tot Beperkt Kwetsbaar (vastgesteld BK), Kwetsbaar (vastgesteld K), Zeer Kwetsbaar (vastgesteld ZK) en PR10-6 (vastgesteld PR10-6*"

**Comment by manuelbeterams** [comment]
dit sluit aan op issue 34

**Comment by PalmJanssen** [comment]
Betekend een wijziging van de waardelijst TypePlaalsgebondenRisico:
Toevoegen: Beperkt Kwetsbaar (vastgesteld BK), Kwetsbaar (vastgesteld K), Zeer Kwetsbaar (vastgesteld ZK) en PR10-6 (vastgesteld PR10-6)
verwijderen: vastgesteld
Vraag: waarom PR10-6? Die zit er al in.
![image](https://user-images.githubusercontent.com/9932784/153180517-d1469244-5ba3-469b-b05c-e2c06b291bcb.png)


![image](https://user-images.githubusercontent.com/9932784/153179715-517de77f-7e9d-42ed-88d1-c3ad922afe26.png)

**Comment by PalmJanssen** [comment]
Werkgroep:
Voor LPG mag vastgesteld niet worden gebruikt maar geldt PR10-6.

nieuwe lijst

PR10-5
PR10-6
PR10-7
PR10-8
vastgesteld BK
vastgesteld K
vastgesteld ZK
gegevenInTransitie

Verwijderen: Vastgesteld

**Comment by PB-GNM** [comment]
Gesloten, omdat het verwerkt is in versie 1.2 en omdat die versie goedgekeurd is.
