### ISSUE TITLE
SDIMEV-42: REV-helpdesk 22 02 0073: mogelijkheid om referentieEVContour zonder evContour in te voeren 

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#46]
Het wijzigingsvoorstel is: Pas aan: de mogelijkheid om referentieEVContour zonder evContour in te voeren.

De achtergrond hierbij is dat dit mogelijk nodig is, zodat alle installaties behorende bij een activiteit uit onderdeel E van bijlage VII van het Bkl (bijvoorbeeld Seveso-inrichting) vanuit het RRGS kunnen worden overgenomen. De suggestie is dit te bespreken met enkele bronhouders van BRZO-omgevingsdiensten of dit gewenst is. 

Eerste reactie Arno: Dit is iets wat in het conversieproces opgepakt kan worden. Geeft het bijvoorbeeld een default contour mee. Zodat je later nog kunt zien dat er een echte waarde moet komen (je kunt er op rapporteren). Geen EVcontour toestaan in het model is niet gewenst

**Comment by PalmJanssen** [comment]
relatie met #22

**Comment by PalmJanssen** [comment]
Het issue lijkt hier te zijn dat bronhouders de EVContour mogelijk niet leveren maar dat de contour door het REV uit de RRGS wordt overgenomen.
komt hier in het model voor (voorbeeld seveso):
![image](https://user-images.githubusercontent.com/9932784/153183203-9a86b849-0bec-455a-9f9b-9d9f581b4357.png)

**Comment by PalmJanssen** [comment]
Werkgroep:
- er zijn situaties dat de PR waarde 'niet wordt gehaald'. In dat geval is er geen contour of aandachtsgebied.
- een voorbeeld is ammoniakkoelinstallatie.
- er zijn situaties van bedrijven met seveso activiteiten waar geen EVcontour bij hoort.
- mogelijkheid om dit ook met een voidable op de relatie te doen. Exclusieve waarde NietVanToepassing.

**Comment by PalmJanssen** [comment]
Opmerking Intern EAP: 
![image](https://user-images.githubusercontent.com/9932784/155362756-4e74142e-44ed-4cc3-8827-f08294c8231c.png)

**Comment by PB-GNM** [comment]
Gesloten, omdat het verwerkt is in versie 1.2 en omdat die versie goedgekeurd is.
