### ISSUE TITLE
SDIMEV-42: REV-helpdesk 22 02 0071: een optioneel/verplicht veld bij referentieEVContour om de BKL/EV-subcategorie te kunnen invullen.

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#47]
Voeg toe: een optioneel/verplicht veld aan referentieEVContour om de BKL/EV-subcategorie te kunnen invullen.

Eerste reactie Arno de Ruijter (ministerie van IenW): Hiervoor geldt dat dit af te leiden is uit de gegevens uit het IMEV en dat het daarmee niet nodig is om mee te leveren. Daarnaast wordt de data van een BH gezien als authentiek, waarom zou je dan gaan valideren op hun inhoudelijke levering?

**Comment by PalmJanssen** [comment]
Zou een algemeen attribuut van ReferentieEVContour worden, dat dan voor alle typen ReferentieEVContour geldt.
Wat zijn die BKL/Ev-subcategorien? Staan die al niet in de EVActiviteit?

Voorbeeld Tanken LPG:
![image](https://user-images.githubusercontent.com/9932784/153184432-865ac08b-bcac-46b5-bbfb-c9847efca1d8.png)

**Comment by PalmJanssen** [comment]
Werkgroep:
- kan later besproken worden
- voor nu parkeren

**Comment by PB-GNM** [comment]
Waar zijn de BKL/EV-sub-categorien te vinden?

**Comment by PB-GNM** [comment]
De lijst met subcategorieën is inmiddels bekend. Er bestaan 111 subcategorieën verdeeld over 33 BKL-EV activiteiten.
De subcategorieën worden opgebouwd uit kenmerken die wel in IMEV gekoppeld zitten zitten aan de EVactiviteit en de referentieEVcontour objecten.

Resterende vraag is:
Waarom is de subcategorie nog gewenst als de informatie al wel in het IMEV zit?

**Comment by PB-GNM** [comment]
Opgelost in versie 1.3.
