### ISSUE TITLE
SDIMEV-42: REV-helpdesk 22 02 0069: Voeg toe: verplicht veld voor locatie_id  aan LocatieActiviteit

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#48]
Kenmerk 22 02 0069

Het wijzigingsverzoek is:
Voeg toe: verplicht veld voor locatie_id  aan LocatieActiviteit om te kunnen filteren op LocatieActiviteit met alle bijbehorende evActiviteiten, referentieEVContouren en evContouren

Eerste reactie Arno de Ruijter (ministerie IenW); Dit is een vraag die hoort bij het “bevragen van de REV”, dat je alle activiteiten wilt zien voor een bepaalde locatie. Daarvoor hoeft er geen IMEV aanpassingen te zijn. Is een applicatie-vraagstuk.
Zou evt bij uitleveren van gegevens ook de verwijzende id’s mee kunnen geven. Maar ook daarvoor geld dat het IMEV bedoelt is voor aanleveren van gegevens. Die hoeft hierop niet te worden aangepast.
Lijkt op issue #16 Waarom hebben de verschillende objecten geen verwijzende sleutels? · Issue #16 · Geonovum/imev-werkomgeving · GitHub

**Comment by PB-GNM** [comment]
Maar de LocatieActiviteit heeft toch al een verplicht id via supertype ExterneVeiligheidsobject?

**Comment by PalmJanssen** [comment]
Er is al een identificatie van LocatieActiviteit:
![image](https://user-images.githubusercontent.com/9932784/153185022-71f0ce65-e912-42f8-97ce-9252b3d8a2d6.png)

**Comment by PalmJanssen** [comment]
Werkgroep:

Gaat erom dat in de conversie het id van het object in het bronhoudersysteem te behouden of te kunnen relateren aan het id in het REV.
Dat zou met LokaalID moeten kunnen lijkt het. Moet in de conversie opgelost worden

Geen IMEV onderwerp.

**Comment by PB-GNM** [comment]
Reacties VTH leveranciers:

1. niet nodig
2. Bij het invoeren van nieuwe locaties in het REV middels de invoermodule wordt al de mogelijkheid geboden om een lokaal id op te geven. Standaard is dit een vrij invulveld, maar deze kan ook worden gegenereerd. Wat ons betreft is hier dus geen verdere IMEV-wijziging voor nodig.
3. Het toevoegen van een lokaal ID in het IMEV om te kunnen refereren naar een id van de objecten in het bronhoudersysteem (= onze VTH-software) lijkt ons een goed idee. De impact is zeer klein. De wens aan onze kant is dan echter wel om ook gegevens vanuit het REV op te kunnen vragen op basis van dat Lokaal ID. Dat maakt het ‘eenmalig’ koppelen/synchroniseren van de gegevens die in het REV staan met de gegevens die al in het bronhoudersysteem staan een stuk eenvoudiger

**Comment by PB-GNM** [comment]
Nen3610id bevat ook een deel met lokaal-id, maar dat is al gevuld met RRGS-id.

**Comment by PB-GNM** [comment]
Verwerkt:
![image](https://user-images.githubusercontent.com/80040145/204305204-831097bf-1b44-4cea-bc71-1afe101e7daa.png)

**Comment by PB-GNM** [comment]
Omdat "lokaal_id" te veel lijkt op het "lokaalID" in het NEN3610ID, is er uiteindelijk voor de naam "bronobjectID" gekozen.
Daarmee is ook duidelijker dat dit bedoeld is voor ID's zoals de bronhouder die intern heeft gebruikt.

**Comment by PB-GNM** [comment]
Opgelost in versie 1.3.
