### ISSUE TITLE
SDIMEV-42: REV-Helpdesk: 22 02 0089: basisvergunningnummer, datumvergunningofmelding en datumlaatstewijziging optioneel maken. 

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#49]
Kenmerk 22 02 0089 
basisvergunningnummer, datumvergunningofmelding en datumlaatstewijziging optioneel maken. 
Dit in verband met het vullen van de REV met gegevens waarvan dit niet (makkelijk) uit de archieven gehaald kunnen worden (vele gasdrukregel- en meetstations en propaantanks die niet zijn geregistreerd in het RRGS)

**Comment by PalmJanssen** [comment]
Werkgroep:
- voidable lijkt de goede optie. Waarde 'niet te achterhalen' als waarde'

**Comment by PalmJanssen** [comment]
verwerkt:

![image](https://user-images.githubusercontent.com/9932784/155363764-6e70d20d-390b-4a08-97bd-932a2e6e07eb.png)

**Comment by PB-GNM** [comment]
Gesloten, omdat het verwerkt is in versie 1.2 en omdat die versie goedgekeurd is.
