### ISSUE TITLE
Multi geometrieën versus single geometrieën

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#5]
nr in eerste issuelijst: 4
Indiener: Nick Naus Geodan

In het   IMEV kennen we een paar locaties (Basisnet en Buisleiding) waarin de   referenties kunnen bestaan uit multi-geometrieen. De referenties zijn:

- Watervervoer
- Wegvervoer
- Spoorvervoer
- Buisleiding

Aan 1 referentie kan 1 PRContour gekoppeld zijn. Een PR Contour is geen multi-geometrie. 
Dit kan toch gekke situaties leiden in het aanleverbestand aan het REV (JSON formaat). 3 buisleiding delen die niet per se aan elkaar liggen kunnen volgens het model horen bij 1 PR Contour wat geen multi-polygon kan zijn. 

**Analyse/Oplossing:**
Aan een ReferentieEVContour kunnen in principe wel meerdere contouren gekoppeld worden conform IMEV, dit is dus wel mogelijk.

**Comment by BrittvanWaveren** [comment]
Beste Paul, hierbij zoals verzocht de reactie van Geodan:

Technische impact: De REV API specificatie moet gewijzigd worden.
