### ISSUE TITLE
SDIMEV-42: REV-helpdesk 22 02 0074: optioneel veld  bij evActiviteit voor mba (kern-mba of foa) conform BAL

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#51]
Kenmerk 22 02 0074 
Voeg toe: een optioneel veld aan evActiviteit om mba (kern-mba of foa) conform BAL in te vullen

Het verzoek is om bij featuretype evActiviteit de mogelijkheid toe te voegen om aan te geven (naast welke categorie uit het Bkl geldt) onder welke milieubelastende activiteit die in het Bal wordt genoemd, de activiteit valt.

**Comment by PalmJanssen** [comment]
Voor mij begrip. Zijn dat de categorieën van Tabel VII? Daar zijn de BKLactiviteiten toch op gebaseerd?

**Comment by PalmJanssen** [comment]
Werkgroep:
- relatie tussen Bkl activiteit en Mba zit niet in model
- die relatie helpt de VTH software om bij de goede Bkl activiteit 'uit te komen'
- een dergelijke relatie tabel helpt de sector, die zou je moeten standaardiseren, publiceren
- bespreek dat met VTH leveranciers. Is een actie voor Geonovum IMEV beheer.

**Comment by PB-GNM** [comment]
Is er een tabel waar de relatie tussen BKL en BAL activiteiten uit blijkt?
Wat is de kardinaliteit van deze relatie?
Bij een 1 op 1 of n op 1, dan ligt het dus vast welke  BAL activiteit bij welke BKL activiteit hoort en kan een tabel volstaan.
Bij n op n ligt het dus niet vast welke BAL activiteit bij welke BKL activiteit hoort en zou de BAL activiteit-code een attribuut kunnen worden.

**Comment by PB-GNM** [comment]
## Aanleiding wijziging
Het verzoek is om bij featuretype EVActiviteit de mogelijkheid toe te voegen om aan te geven onder welke milieubelastende activiteit die in het BAL wordt genoemd, de activiteit valt.

## Voorgestelde wijziging
Optioneel veld bij EvActiviteit voor MBA (kern-mba of foa) conform BAL

![image](https://user-images.githubusercontent.com/80040145/192291561-ccb7c377-091a-4246-8155-b6e47bc8f5ea.png)

## Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? **dataprovider en gebruiker REV en Softwareleveranciers**
- Verandert de semantiek van de objecten? **Nee**
- Heeft het impact op het json-schema? **Ja**

## Prioriteit
Middel

## Toelichting
Er kunnen meerdere BAL-activiteiten bij een BKL-activiteit horen. Als dat altijd dezelfde zijn per BKL-activiteit, dan is het beter om dit in een aparte tabel bij te houden dan in het REV en dus IMEV. Als het per instantie kan verschillen hoort het wel in het REV en dus ook in het IMEV.

**Comment by PB-GNM** [comment]
Moet dit met een enumeratie? Vergt wel extra onderzoek.
voorlopig huidige lijst met volledige tekst en artikelnr met overig.

**Comment by PB-GNM** [comment]
De expertgroep adviseert een mogelijkheid in te bouwen om meerdere MBA's per BKL/EV-activiteit te kunnen toevoegen. Bij enkele BKL/EV-activiteiten kunnen namelijk meerdere MBA's van toepassing zijn. Een voorstel voor een enumeratielijst kan door de expertgroep worden aangeleverd;

**Comment by PB-GNM** [comment]
Dit moet ook toegevoegd worden aan ActiviteitRestCategorie #73

**Comment by PB-GNM** [comment]
Bijgevoegde lijst is toegevoegd aan de enumeratie voor MBAActiviteiten.

[20221128_voorstel_enumeratielijst_mba_en_imev_match_tabel.xlsx](https://github.com/Geonovum/imev-werkomgeving/files/10124271/20221128_voorstel_enumeratielijst_mba_en_imev_match_tabel.xlsx)

**Comment by PB-GNM** [comment]
Opgelost in versie 1.3.
