### ISSUE TITLE
Fout in IMEV tekst bij Wegen, anders dan het basisnet

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/imev-werkomgeving#53]
Fout in tekst bij dit deelmodel zie gele omlijning.

Heeft geen impact op software.

https://docs.geostandaarden.nl/imev/imev/#EAID_5CD4419F_EF30_4cf2_94EA_E99E1EBCE2C0

![image](https://user-images.githubusercontent.com/9932784/153189259-0c753525-bac3-4a95-8dcd-d7a0684f2da4.png)

**Comment by PB-GNM** [comment]
Gesloten, omdat het verwerkt is in versie 1.2 en omdat die versie goedgekeurd is.
