### ISSUE TITLE
Excel met ActiviteitenIMEV-Referentiepunten: status? en hoe publiceren?

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/imev-werkomgeving#55]
Er is een excel bestand genaamd ActiviteitenIMEV referentiepunten.

Dit bestand bevat twee dingen:
1) De relatie tussen activiteit en de referentieobjecten. Welke referentieobjecten horen bij welke activiteit.
Bijvoorbeeld:
Bij de activiteit TankenLPG horen als ReferentieEVContour: SamengesteldeReferentie, Vulpunt, Leiding, Opslagreferentie en Tankzuil

2) De relatie tussen activiteit en deze onderwerpen: PR, B-AG, E-AG, E-AGvw en CivE-AG.
Bijvoorbeeld:
Bij de activiteit TankenLPG kan voor TypePlaatsgebondenRisico de waarde Vastgesteld en PR10-5 worden gebruikt.
PR = TypePlaatsgebondenRisico.
B-AG = Brand-Aandachtsgebied 
E-AG = Explosie-Aandachtsgebied
G-AG = Gifwolk-Aandachtsgebied 
E-AGvw = Explosie-Aandachtsgebied  ....
CivE-AG = Civiele explosie-Aandachtsgebied 

1. begrijp ik en kan gebruikt worden als validatieregel op een JSON bestand.

2. PR verwijst mogelijk naar toegestane waarden uit de enumeratielijst TypePlaatsgebondenRisico. De andere naar toepassen Aandachtsgebied  met berekende of vastgestelde contour.

De lijst bevat wat mij betreft modelinformatie en zou dan in het IMEV document als bijlage kunnen worden opgenomen.

 
[ActivteitenIMEV Referentiepunten DEF.xlsx](https://github.com/Geonovum/imev-werkomgeving/files/8264067/ActivteitenIMEV.Referentiepunten.DEF.xlsx)

**Comment by PB-GNM** [comment]
Ik neem aan dat het alleen om sheet "blad1" gaat en niet om die die daar nog voor zit: "Match referenties".

**Comment by PB-GNM** [comment]
Wat betekenen de gele lijnen?

**Comment by PB-GNM** [comment]
tabel los publiceren op : https://register.geostandaarden.nl/.
geldt ook voor andere tabellen.

**Comment by PalmJanssen** [comment]
Er zijn een paar vragen: 
- is er een tekst die de inhoud en doel van de tabellen beschrijft? Zo niet dan moet die wel opgesteld worden.
- zijn de tabellen actueel.

We kunnen de tabellen opnemen in het register.geostandaarden.nl  en ze refereren vanuit de imev document. Ik denk in een bijlage.

**Comment by PB-GNM** [comment]
Opgelost in versie 1.3.
