### ISSUE TITLE
Toevoegen van een optioneel veld 'omschrijving' aan 'SamengesteldeReferentie' (SDIMEV-45)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#56]
Ingebracht wijzigingsvoorstel van Boudewijn de Hoop via Arno de Ruijter: 
Het toevoegen van een optioneel veld 'omschrijving' aan 'SamengesteldeReferentie' (zoals bij 'SevesoReferentie');
Zonder deze toevoeging kan geen goede duiding (bijvoorbeeld NAAM_INSTALLATIE uit het RRGS) worden gegeven aan referentieEVContouren, waarbij (vrijwel) uitsluitend het object ‘SamengesteldeReferentie’ kan worden gebruikt. Dit geldt onder andere voor VII-E3, VII-E5, VII-E4.

**Comment by PB-GNM** [comment]
![image](https://user-images.githubusercontent.com/80040145/163991977-c3730e60-2b48-464b-b35a-221688f2790e.png)

**Comment by PalmJanssen** [comment]
Verwerkt:

![image](https://user-images.githubusercontent.com/9932784/164486625-d50d3743-1a0d-4011-8de7-ddf374919f7d.png)

omschrijving: Beschrijving in woorden van de betreffende SamengesteldeReferentie.

**Comment by PB-GNM** [comment]
Gesloten, omdat het verwerkt is in versie 1.2 en omdat die versie goedgekeurd is.
