### ISSUE TITLE
Toevoegen optie 'opslagplaats' in enumeratie 'typeOpslagreferentie' (SDIMEV-45)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#57]
Ingebracht wijzigingsvoorstel van Boudewijn de Hoop via Arno de Ruijter:
Het toevoegen optie 'opslagplaats' in enumeratie 'typeOpslagreferentie' voor een meer passende omschrijving van een opslagplaats voor verpakte gevaarlijke stoffen (onder andere activiteit VII-A11 en VII-B3). Op grond van IMEV v1.2 moet gekozen worden voor ‘overig’

**Comment by PB-GNM** [comment]
Mij lijkt "overig" juist beter, want dat het een opslagplaats is geldt voor alle typen, want dat zit al in de naam van het object: 
 "Opslagreferentie" waar het attribuut "typeOpslagreferentie" bij hoort.

**Comment by PB-GNM** [comment]
Niet elke opslagreferentie is een opslagplaats
Tyora zoekt een definitie van opslagplaats. 
Het is een soort vloeroppervlak en zit dus niet ergens in.

**Comment by PalmJanssen** [comment]
Verwerkt:

Opslagplaats: Iedere plek of plaats waar gevaarlijke stoffen worden opgeslagen, zoals een bouwwerk of een onderdeel daarvan, een brandwerende constructie die geen onderdeel is van een bouwwerk, een brandveiligheidskast, een paardenbox of een andere ruimtelijk afgescheiden plaats.



![image](https://user-images.githubusercontent.com/9932784/165248694-8ffab86b-118f-40ae-8fd2-e59b8f6474e6.png)

**Comment by PB-GNM** [comment]
Gesloten, omdat het verwerkt is in versie 1.2 en omdat die versie goedgekeurd is.
