### ISSUE TITLE
relatie tussen LocatieEVActiviteit en EVActiviteit

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/imev-werkomgeving#62]
De relatie heeft in het EA UML een fout in de definitie. de drie xxx.
xxxVerwijzing naar de EVActiviteit die op de locatie wordt verricht.

Geen effect op model, implementatie of documentatie omdat die definitie niet wordt gebruikt. Moet wel netjes gemaakt worden in EA.

**Comment by PalmJanssen** [comment]
Verwerkt in uml

**Comment by PB-GNM** [comment]
Opgelost in versie 1.3.
