### ISSUE TITLE
Tagged values van de Relatierollen zijn niet toegekend

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/imev-werkomgeving#63]
De Stereotypen Relatierol bij de associaties hebben geen tagged values. Dit is nu nog niet van belang.

Oplossing: De tagged values moeten in EA gesynchroniseerd worden.

**Comment by PalmJanssen** [comment]
**Analyse:**

Dit is een technisch probleem van Enterprise Architect. Tagged values toepassen op relatierollen werkt niet goed.
Dit heeft geen impact op het model wel voor het automatisch genereren van schema's en documentatie.

**Oplossing**
Via een synchronisatie van het stereotype relatierol worden de tagged values wel toegekend. Maar...... EA heeft een bug waardoor er voor relatierollen geen waarden met de hand ingevuld of gewijzigd kunnen worden. De oplossing is om de tagged values van relatierollen te negeren en de tagged values voor de relatie toe te passen op de relatierol. Dit is van belang voor het tagged value''**Mogelijk geen waarde**"  dat default op nee staat, terwijl er voor een relatierol soms ja nodig is. In dat geval dus naar de waarde bij de relatiesoort kijken

**Comment by PB-GNM** [comment]
Opgelost in versie 1.3.

**Comment by PB-GNM** [comment]
zie
https://github.com/Geonovum/MIM-Werkomgeving/blob/master/UML%20profieltooling/werkversie1.1.1/README.md#4-toepassen-toolbox-item-relatierol 
en 
https://github.com/Geonovum/MIM-Werkomgeving/blob/master/UML%20profieltooling/werkversie1.1.1/README.md#5-updaten-mim-versie-in-bestaand-informatiemodel

**Comment by PB-GNM** [comment]
Opgelost in [versie 2.0](https://docs.geostandaarden.nl/imev/def-im-imev-20231031/).
