### ISSUE TITLE
Buisleidingen: Af te stappen van het bijhouden van datum geldigheid en uit het IMEV (SDIMEV-46, REV-262)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#65]
Het wijzigingsvoorstel van Muneesh Malgie is om voor buisleidingen af te stappen van het bijhouden van datum geldigheid en dit uit het IMEV te halen.

- IMEV vraagt voor elk object een begin en eind geldigheid. Die geldigheid gaat over de gewijzigde kenmerk van een object, dus alleen als een kenmerk wijzigt, ontstaat een nieuwe versie van het object met nieuw startdatum geldigheid. 
- Voor buisleidingen worden dit dan “gegenereerde” datumvelden, die geen relatie hebben met gewijzigde kenmerken. 
- Gebruikers kunnen dan ook niet vertrouwen of een kenmerk ook daadwerkelijk is gewijzigd als er een nieuwe startdatum is ingevuld. 
- Voorstel voor wijziging zou dan zijn om af te stappen van het bijhouden van datum geldigheid en dit uit het IMEV voor buisleidingen te laten vervallen

**Comment by PalmJanssen** [comment]
**Analyse**

De materiele historie van de BKLActiviteit Buisleiding wordt hier gemodelleerd en wordt algemeen gebruikt voor alle IMEV objecten:
![image](https://user-images.githubusercontent.com/9932784/185583966-3d92d680-7d73-48b6-922d-593c24698d0b.png)

Het gaat voor de BKLActiviteit Buisleiding over de momenten dat dat object in de werkelijkheid ontstaat en verandert van eigenschappen, dus historie opbouwt. De werking daarvan is niet anders dan bij andere BKLActiviteiten.
Opmerking: Ik verwacht dat voor de EVActiviteiten in algemene zin de materiele historie gelijk loopt met de formele historie

**Voorstel oplossing**
Geen aanpassing

**Comment by PalmJanssen** [comment]
Iets meer achtergrond:

In principe gaat het om de datum dat een activiteit van belang is binnen deze wetgeving.

De waarde voor beginGeldigheid is vaak de datum dat een vergunning wordt uitgegeven. Omdat de activiteit Buisleiding geen vergunning heeft is daar geen datum van te halen. De beginGeldigheid moet dus ergens anders op worden gebaseerd. In principe gaat het om de datum dat een activiteit een status heeft binnen deze wetgeving.

**Comment by PB-GNM** [comment]
Op 6 december is aangegeven dat de hier boven bedoelde extra toelichting toch niet nodig is.
