### ISSUE TITLE
Correctere invulling van de adressen of locatie-aanduidingen (SDIMEV-55)

### ISSUE THREAD

**Issue by geurtsf** [Geonovum/imev-werkomgeving#70]
Vraag van Rianne D. 

Kunnen jullie de volgende IMEV-aanpassing doorgeven aan Geonovum?!

Geachte collega’s van Geonovum,
Kunnen jullie het IMEV zodanig aanpassen dat het invullen van de adressen of locatie-aanduidingen correcter kan plaatsvinden?! Het gaat om het volgende:
1.	Adres opsplitsen in de standaardadresopbouw van de BAG: straat, huisnummer, postcode en woonplaats;
2.	Verplicht is het invullen van (één van de twee):
•	hetzij een BAG-adres of (als dat niet kan)
•	hetzij een locatieomschrijving. 
Momenteel is het niet goed verwerkt, begrijp ik, in de informatiemodellen. Nu kun je alleen een locatieomschrijving intypen als je ook een adres invult. Dat is suf, want dat nodigt uit tot databasevervuiling. Ongewenst.

**Comment by PB-GNM** [comment]
Dit lijkt hetzelfde als #52

**Comment by PB-GNM** [comment]
Deze is echt hetzelfde als #52 en wordt daarom gesloten.

**Comment by geurtsf** [comment]
Helemaal goed

Dank voor de informatie.

Groeten,
Frans

Van: Pieter Bresters ***@***.***>
Verzonden: woensdag 31 augustus 2022 08:50
Aan: Geonovum/imev-werkomgeving ***@***.***>
CC: Geurts, Frans (WVL) ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Geonovum/imev-werkomgeving] Correctere invulling van de adressen of locatie-aanduidingen (SDIMEV-55) (Issue #70)


Deze is echt hetzelfde als #52<https://github.com/Geonovum/imev-werkomgeving/issues/52> en wordt daarom gesloten.
