### ISSUE TITLE
Enumeratie DoorzetCategorie wel in doc maar wordt niet gebruikt

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/imev-werkomgeving#72]
## Waar zit de fout?

(https://docs.geostandaarden.nl/imev/imev/#detail_class_Waardelijsten_DoorzetCategorie)

relatie met #40 

## Wat is de fout?

Deze enumeratie wordt nergens (meer) gebruikt.

## Wat moet het worden? [optioneel]

Enumeratie uit de documentatie verwijderen afhankelijk van resultaat #40.

**Comment by PB-GNM** [comment]
#40 is uitgesteld, dus niet afgesteld, dus ik stel voor dat we hem er nog in laten.
Daarom stel ik voor dat dat we deze ook label wontfix geven net als #40

**Comment by PB-GNM** [comment]
Voor de versie 2.0 is die uit het model gehaald, omdat die daar (nog) niet wordt gebruikt.
Hij is in Enterprise Architect project in een tijdelijk mapje gezet zodat hij ook weer snel teruggehaald kan worden.

**Comment by PB-GNM** [comment]
Opgelost in [versie 2.0](https://docs.geostandaarden.nl/imev/def-im-imev-20231031/).
