### ISSUE TITLE
restcategorie die in het RRGS zitten, maar niet in het REV passen (SDIMEV-58)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#73]
## Aanleiding wijziging
Er is behoefte aan een restcategorie voor Activiteiten die in het RRGS zitten, maar niet in het REV passen.

## Voorgestelde wijziging
Restcategorie van EVActiviteiten toevoegen.

## Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? **Softwareleveranciers, dataproviders van de restcategorieën, gebruikers**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Ja er komt een heel diagram bij het IMEV**
- Heeft het impact op het json-schema? **Ja**

## Prioriteit
**hoog**

## Toelichting
Voor deze nieuwe categorie moet nog vastgesteld worden welke subtypes van de basisobjecten voor mogen komen.

**Comment by PB-GNM** [comment]
wel doen met subtypes die vanuit de expertgroep nog wordt aangeleverd.

**Comment by PB-GNM** [comment]
De expertgroep adviseert om:
- de volgende naam/titel te gebruiken voor de Restcategorie Activiteit: "Restcategorie"; 
- eventueel een optioneel veld "omschrijving'' aan activiteit "Restcategorie" toe te voegen om een nadere duiding te kunnen geven aan de Restcategorie; het opnemen van een optioneel veld "omschrijving" bij elk referentie-object is echter relevanter;
- alle voorkomende referentie-objecten bij BKL/EV-activiteiten hieronder te plaatsen; met name de referenties "OpslagReferentie", "Bewaarplaats", "Bufferbewaarplaats", "Machinekamer", "Leiding", "OpstelplaatsVoertuig" en "SamengesteldeReferentie" zijn relevant;
- een optioneel veld "omschrijving" aan deze referentie-objecten toe te voegen (zie #47) om een nadere duiding te kunnen geven aan het referentie-object; 
- in ieder geval de EV-contouren van type "PRContour" (met bijbehorende enumeratie) te koppelen aan de referentie-objecten; evenals bij de BKL/EV-activiteiten is er soms geen EV-contour (EV-contour is dan voidable: nietVanToepassing);
- bij voorkeur ook "ExplosieAandachtsgebiedVuurwerk", "CivielExplosieAandachtsgebied" hieronder te plaatsen, om bij de conversie eventueel de veiligheidsafstanden van meldingsplichtige vuurwerkverkooppunten en opslagplaatsen met munitie (veelal contouren met afstand = 8 meter) als ExplosieAandachtsgebiedVuurwerk of CivielExplosieAandachtsgebied (type B) te kunnen opnemen (in plaats van Vastgestelde afstand BK/K/ZK).

**Comment by PB-GNM** [comment]
Ook volgende referentieEVContouren:
-vulput
-tankzuil
-ander insluitsysteem

Voorlopig geen extra omschrijvingsveld bij de EVactiviteit, want die kan je al kwijt in de omschrijving van het referentieobject.

**Comment by PalmJanssen** [comment]
Toevoeging naar aanleiding van review van de conceptoplossing door de expertgroep.

1. Aandachtsgebied (incl. ExplosieAandachtsgebiedVuurwerk en CivielExplosieAandachtsgebied) verwijderen;
Toelichting/argument: Volgens het BKL geldt een aandachtsgebied uitsluitend voor aangewezen REV-activiteiten en dus niet voor Restcategorie-activiteiten.

2. Onder EVContour toevoegen OverigeContour, met de volgende attributen
- \<< keuze>>afstandOfGeometrie: AfstandOfGeometrieOverigeContour
- typeOverigeContour: TypeOverigeContour
        met enumeratiewaarden: Vastgesteld Vuurwerk, Vastgesteld Ontplofbaar
- aardRisico: CharacterString [0..1]
<<Attribuutsoort, voidable>> maatgevendeStof: StofOfStofcategorie

Toelichting: Rond referenties van een meldingsplichtige vuurwerkopslag of opslag van ontplofbare stoffen zijn veelal afstanden of geometrieen van contouren opgenomen in het RRGS. Ook op grond het BAL gelden rond deze referenties vaste afstanden/contouren (zie o.a. art. 4.1042 BAL). In het BKL is echter niet opgenomen dat deze moeten worden geregistreerd. Ze moeten dus als Restcategorie worden beschouwd.  
Een vastgestelde afstand bij een meldingsplichtige vuurwerkopslag of opslag van ontplofbare stoffen is geen Plaatsgebonden Risicocontour (of: "PRContour") en wordt in het BKL (met name bijlage VII) ook niet  aangeduid als "Afstand plaatsgebonden risico". 
Daarom wordt voorgesteld om voor de vastgestelde afstanden/contouren rond meldingsplichtige referenties voor vuurwerkopslagen en civiele opslag van ontplofbare stoffen een afwijkende definitie te hanteren, bijvoorbeeld "OverigeContour".

**Comment by PB-GNM** [comment]
Opgelost in versie 1.3.
