### ISSUE TITLE
reactietijd­Noodstop type 'Boolean' ipv 'Integer'

### ISSUE THREAD

**Issue by PeterFrans** [Geonovum/imev-werkomgeving#78]
## Waar zit de fout?

In het IMEV heeft 'Tanken­LNGVoertuig­Werktuig' het attribuut 'reactietijd­Noodstop'. Dit attribuut heeft de definitie: 
	
Reactietijd noodstopvoorziening = 5 sec Ja/Nee. 

Verder staat in het informatie model bij de toelichting van het attribuut:

'(..) Alleen als aannemelijk gemaakt kan worden dat er zowel bij de LNG-tankwagen als bij de LNG-opslagtank 
binnen 5 seconden kan worden ingegrepen zodat de uitstroming stopt, wordt hier «ja» gekozen.'

en:

'(...) Bij alleen ingrijpen door de operator (manueel) is het antwoord «nee».'erwijzing naar plaats(en) in de tekst waar de fout zit.

## Wat is de fout?

Volgens het gegevenswoordenboek (versie 01/03/2021) is dit attribuut van het type 'integer'. 

## Wat moet het worden? [optioneel]

Dit zou naar mijn idee het type 'Boolean' moeten zijn (Ja|Nee).

**Comment by PB-GNM** [comment]
Ook aangepast voor attribuut voordruk.

**Comment by PB-GNM** [comment]
Opgelost in versie 1.3.
