### ISSUE TITLE
A12 Opstellen van voertuigen: OpstelplaatsVoertuig of OpslagReferentie?

### ISSUE THREAD

**Issue by PeterFrans** [Geonovum/imev-werkomgeving#79]
## Waar zit de fout?

In de documentatie (IMEV1.2 en IMEV1.3rc1) staan in paragraaf 6.1.15 (VII-A.12 Opstellen van voertuigen, opleggers of aanhangers met gevaarlijke stoffen - detail) **in het schema** als inrichtingselementen:

1. **OpstelplaatsVoertuig**;
2. SamengesteldeReferentie.

In de beschrijving onder het schema staat echter: 

_Voor de Referentie­EVContour zijn van belang de locatie:

**Opslag­Referentie**
Samengestelde­Referentie_

## Wat is de fout?

De informatie in het schema en in de beschrijving is inconsequent. 

## Wat moet het worden? [optioneel]

Waarschijnlijk moet in de beschrijving 'OpslagReferentie' worden vervangen door 'OpstelplaatsVoertuig'.

**Comment by PB-GNM** [comment]
Opgelost in versie 1.3.
