### ISSUE TITLE
IJsvalgebied verwijderen uit model

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#8]
nr in eerste issuelijst: 7
Indiener: Antea Group

IJSvalgebied is nu een type EVContour bij 'Windturbine' activiteiten. Dit object heeft geen 'wettelijke basis' daarom verwijderen is het verzoek

**Analyse/Oplossing**
Verwijderen

**Comment by PalmJanssen** [comment]
Objecttype IJsvalgebied verwijderd uit het model. Verplaatst naar deprecated
