### ISSUE TITLE
IMEV 1.3: Inconsistentie aantalBevoorradingen vs reactieTijdNoodstop/voordruk

### ISSUE THREAD

**Issue by PeterFrans** [Geonovum/imev-werkomgeving#80]
## Aanleiding wijziging
 
Er zit een inconsistentie tussen de volgende attributen:

https://docs.geostandaarden.nl/imev/imev/#detail_class_IMEVBasis_BevoorradingCategorieOfExactAantal
https://docs.geostandaarden.nl/imev/imev/#detail_attribute_BKLActiviteiten_TankenLNGVoertuigWerktuig_reactietijdNoodstop
https://docs.geostandaarden.nl/imev/imev/#detail_attribute_BKLActiviteiten_TankenLNGVoertuigWerktuig_voordruk

Voor 'aantalBevoorradingen' is in IMEV 1.3 gekozen voor de volgende oplossing:
https://github.com/Geonovum/imev-werkomgeving/issues/39
![image](https://user-images.githubusercontent.com/9932784/202703373-d01b359c-ba9f-45b9-9a11-bd26e5b07c2e.png)

Voor reactieTijdNoodstop en Voordruk is (op mijn verzoek) gekozen om het datatype te veranderen van 'integer' naar 'boolean':
https://github.com/Geonovum/imev-werkomgeving/issues/78
(note: Bij issue 39 is terecht door de expertgroep is gewezen op het aandachtspunt dat extra conversie evt nodig zou zijn. Dat is bij issue 78 ook het geval maar niet ondervangen)

Dit zijn verschillende implementaties in de standaard van hetzelfde 'probleem' waarbij een keuze gemaakt moet worden tussen een categorie of exact aantal.

Voordelen van de gesuggereerde oplossing:

1. Consistent;
2. Geen conversie nodig, beperking risico. 

## Voorgestelde wijziging

De oplossing waar voor gekozen is in issue 39 (waarde ofwel een keuze uit een enumeratie, ofwel een integer) zou ook moeten worden toegepast voor reactieTijdNoodstop en Voordruk. Tevens moet worden uitgezocht of deze inconsistentie zich ook voordoet bij andere waarden in de standaard. De voorgestelde wijziging heeft volgend effect op model:

Was:
![image](https://user-images.githubusercontent.com/9932784/231497193-d2458429-b5a4-48a5-9484-ac31bbe16a78.png)

Wordt:
![image](https://user-images.githubusercontent.com/9932784/231497127-7820789a-d5b9-45d4-960c-47109fa5c577.png)

## Impactanalyse

Wie gaat er wat van merken? Dataleveranciers en software leveranciers
Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? Ja t.o.v. situatie 1.3 en Nee t.o.v. situatie 1.2
Heeft het impact op het json-schema? Ja, want er wordt voorgesteld datatypen te veranderen en keuzes in te bouwen

**Comment by PalmJanssen** [comment]
De voorgestelde wijziging heeft volgend effect op model:

Was:
![image](https://user-images.githubusercontent.com/9932784/231497193-d2458429-b5a4-48a5-9484-ac31bbe16a78.png)


Wordt:
![image](https://user-images.githubusercontent.com/9932784/231497127-7820789a-d5b9-45d4-960c-47109fa5c577.png)

**Comment by JanCasSmitGeonovum** [comment]
Expert overleg IMEV 31 MEI 2023, thema Inhoud van het REV

Voorgestelde wijziging inhoudelijk akkoord? Ja

1.	Wat adviseren we de adviesgroep: doen , is een Y wijziging
2.	Wat is de prioriteit (midden)
3.	Klopt de beschreven impact (Ja)

Moeten software leveranciers benaderd worden voor dit issue: niet nodig.

**Comment by PB-GNM** [comment]
Opgelost in [versie 2.0](https://docs.geostandaarden.nl/imev/def-im-imev-20231031/).
