### ISSUE TITLE
'OpslagReferentie' niet in toelichting 'Seveso' en 'OpslagVerpakt_TeBerekenenAfstandVergunningplicht'

### ISSUE THREAD

**Issue by PeterFrans** [Geonovum/imev-werkomgeving#82]
## Waar zit de fout?

- 6.1.29 VII-E.6 Seveso-inrichting-detail;
- 6.1.28 VII-E.5 Opslaan van gevaarlijke stoffen in verpakking - detail

## Wat is de fout?

In de toelichting bij het schema wordt bij beiden de 'OpslagReferentie' niet genoemd.

## Wat moet het worden? [optioneel]

'OpslagReferentie' moet worden toegevoegd op de plaatsen waar de fout zit.

**Comment by PB-GNM** [comment]
Verwerkt in Versie 2.0.

**Comment by PB-GNM** [comment]
Opgelost in [versie 2.0](https://docs.geostandaarden.nl/imev/def-im-imev-20231031/).
