### ISSUE TITLE
OpslagtankPropeen_VasteAfstandVergunningplicht - Fout in naam

### ISSUE THREAD

**Issue by PeterFrans** [Geonovum/imev-werkomgeving#83]
## Wat is de fout?

Er zit een fout in de naam 'Opslagtank**Propeen**_VasteAfstandVergunningplicht' bij de toelichting van het schema.

## Wat moet het worden? [optioneel]

6.1.17 VII-B.2 'Opslagtank voor gassen - detail.  'Opslagtank**PropaanPropeen**_VasteAfstandVergunningplicht'

**Comment by PB-GNM** [comment]
Verwerkt in versie 2.0.
