### ISSUE TITLE
Constraint toevoegen: Samengestelde referentie mag niet voorkomen bij vastgestelde afstanden (REV-272, SDIMEV-54)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#84]
## Aanleiding wijziging
Samengestelde referenties mogen niet voorkomen bij vastgestelde afstanden bij activiteiten. 
Dit staat niet goed in het IMEV. 

## Voorgestelde wijziging
Constraint toevoegen: SamengesteldeReferentie mag niet voorkomen als Aandachtsgebied.categorieAandachtsgebied="vastgesteld"

## Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? dataproviders en de softwareleveranciers die deze validatie moeten inbouwen
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? Nee
- Heeft het impact op het json-schema? Waarschijnlijk niet
- De bestaande data in het REV moet hier dan wel met terugwerkende kracht op gecontroleerd worden.
- X-, Y- of Z-wijziging: **Z**
- Er zal nog wel in de bestaande data gecontroleerd moeten worden in hoeverre daar aan deze constraint voldaan wordt.

## Prioriteit
midden

## Toelichting
Ruimte voor extra toelichting. Bijvoorbeeld alternatieven die je overwogen hebt.

**Comment by PalmJanssen** [comment]
Activiteiten waarbij vastgestelde afstanden zijn bepaald.

Wordt daar alleen dit model (en activiteit) mee bedoeld?
https://docs.geostandaarden.nl/imev/imev/#EAID_D09E42B5_89F1_4d9d_8F06_7C73AE188015

Zo ja dan is met dit model bepaald dat er geen SamengesteldeReferentie is toegestaan voor deze activiteit. Er is echter geen constraint opgenomen die dat valideert. Maar dat geldt voor meerdere situaties.

**Comment by PB-GNM** [comment]
Nee, het komt bij meerdere activiteiten voor. bv ook in : https://docs.geostandaarden.nl/imev/imev/#EAID_41CAAAC7_2181_4e76_9B88_8552EE982C1A

**Comment by PB-GNM** [comment]
Opgelost in [versie 2.0](https://docs.geostandaarden.nl/imev/def-im-imev-20231031/).
