### ISSUE TITLE
Verbeter 'PandIdentificatie': Definitie, kardinaliteit en parent object

### ISSUE THREAD

**Issue by PeterFrans** [Geonovum/imev-werkomgeving#86]
## Aanleiding wijziging

- Een 'pandIdentificatie' is een attribuut van een 'LocatieActiviteit' in het IMEV 1.3;
- De definitie is: 'De unieke aanduiding van een pand middels de BAGid' (6.1.50.22. tabel 'overzicht attributen);
- Het heeft een kardinaliteit [0 .. 1]. 

Het is in het IMEV niet duidelijk van welk pand het BAGid geregistreerd mag worden. Er zijn meerdere mogelijkheden:

1. Het pand / de panden waarbinnen zich een of meerdere EV activiteiten (referentieEVContouren) bevinden;
2. Het pand / de panden waarbinnen zich een of meerdere BAG verblijfsobjecten (dus met o.a. nummeraanduiding) bevinden;
3. Het pand / de panden die voldoen aan een ander criterium dat nog niet gedefinieerd is.

Aangezien het hier om externe veiligheidsrisico's gaat, lijkt optie 1 mij het meest waarschijnlijk. Maar omdat een EV activiteit geen geometrie heeft, is het waarschijnlijk beter om een pand te relateren aan een 'referentieEVContour'.

## Voorgestelde wijziging

1. Neem in 6.1.50.22 in de tabel 'overzicht attributen' in de definitie op van welk pand het id moet worden opgenomen. Bijvoorbeeld (aangenomen dat het om panden met referentieEVContouren gaat):

_'De unieke aanduiding van een pand waarbinnen zich een of meerdere referentieEVContouren bevinden, middels de BAGid'_

 2. Pas evt de kardinaliteit van [0 .. 1]  aan naar [0 .. *]. Reden:
 - Geen, een of meerdere panden kunnen bestaan met (of zonder) een of meerdere referentieEVContouren;
 - Geen, een of meerdere panden kunnen bestaan met (of zonder) een of meerdere verblijfsobjecten;
 - Geen, een of meerdere panden kunnen  bestaan met (of zonder) een of meerdere 'ander criterium' (?).

3. Verplaats het attribuut 'pandIdentificatie' van het objecttype 'LocatieActiviteit' naar het objecttype 'ReferentieEVContour ' (alleen als de 'pandIdentificatie' gerelateerd is aan (een) referentieEVContour).
![image](https://user-images.githubusercontent.com/80040145/234585211-6817c948-2dec-4b53-9736-f9bcb25ca195.png)

4. Pas in 6.1.50.19 in de tabel 'overzicht attributen' de definitie aan van de geometrie:
_De tweedimensionale geometrische representatie van een kwetsbare gebouw, bestaand uit de geometrie van een of meer BAG panden._ Maar dit hoor eigenlijk bij #92

## Impactanalyse

- Wie gaat er wat van merken? **Dataprovider, en softwareleveranciers als kardinaliteit ook aangepast wordt of als het attribuut verplaatst wordt.**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Ja**
- Heeft het impact op het json-schema?**Ja, als kardinaliteit ook aangepast wordt of als het attribuut verplaatst wordt.**

## Prioriteit
midden

## Toelichting
De voorgestelde wijziging zorgt voor meer duidelijkheid bij bronhouders over wat ze aan moeten leveren. Ook maakt het mogelijk  volledigere data van een hogere kwaliteit aan te leveren.

NB: 
Voor andere BAG attributen ('adresseerbaar object', 'adres', 'oppervlakte', 'gebruiksdoeleinden') zouden de definities, kardinaliteit en parent objecttype op een analoge manier verbeterd moeten worden, op basis van analoge argumenten (definitie 'adres' is ook niet geupdatet nav BAGid wijziging);

**Comment by PeterFrans** [comment]
Zie ook: https://github.com/Geonovum/imev-werkomgeving/issues/41

**Comment by JanCasSmitGeonovum** [comment]
Expert overleg IMEV 16 MEI 2023, thema aansluiten op andere registraties

Voorgestelde wijziging inhoudelijk akkoord?    ja en nee, gedeeltelijk met met aanpassing
Onderdeel 1: Doen (hoe volgt later)
Onderdeel 2: later doen zie *
Onderdeel 3: later doen zie *
Onderdeel 4: zie wijzigingsbesluit #92 Is positief op besloten op voorstel.

1)	Wat adviseren we de adviesgroep: zie opsomming boven.
2)	Wat is de prioriteit (Midden)
3)	Klopt de beschreven impact (Ja)

*Pandidentificatie, waar komt het attribuut vandaan en wat is het doel en wat moet de kardinaliteit worden,  wordt verder uitgezocht door Robby Veders

**Comment by PB-GNM** [comment]
Robby heeft navraag gedaan over de nut en noodzaak van het attribuut pandidentificatie.
Het blijkt eigenlijk na de wijziging n.a.v. issue https://github.com/Geonovum/imev-werkomgeving/issues/52 helemaal niet meer nodig. Evenzo lijkt het attribuut [adresseerbaar­Object­Identificatie](https://docs.geostandaarden.nl/imev/imev/#detail_attribute_IMEVBasis_LocatieActiviteit_adresseerbaarObjectIdentificatie) niet meer nodig.
Ook tijdens de expertgroep van 17 mei was men het eens dat deze twee attributen er eigenlijk uit kunnen.
Het nieuwe voorstel wordt dus het verwijderen van deze twee attributen.

**Comment by PB-GNM** [comment]
De REV-expertgroep heeft in het overleg van 8-8-2023 ook goedkeuring gegeven aan het verwijderen van de 2 attributen.

**Comment by PB-GNM** [comment]
Tijdens het softwareleveranciersoverleg van 7 juni is er geen bezwaar geuit tegen het verwijderen van deze 2 attributen.

**Comment by PB-GNM** [comment]
Opgelost in [versie 2.0](https://docs.geostandaarden.nl/imev/def-im-imev-20231031/).
