### ISSUE TITLE
Object 'OpslagtankPropaanPropeenVasteAfstand_GeenVergunningplicht' mist attribuut 'inhoud'

### ISSUE THREAD

**Issue by PeterFrans** [Geonovum/imev-werkomgeving#87]
## Aanleiding wijziging

Het object 'OpslagtankPropaanPropeenVasteAfstand_GeenVergunningplicht (A7) heeft een 'Vulpunt' en/of een 'OpstelplaatsVoertuig'. 
Bij het object 'OpslagtankPropaanPropeenVasteAfstand_GeenVergunningplicht' ontbreekt naar mijn idee het attribuut 'inhoud'.

Beschouw het volgende:

- Voor de activiteit A7 met referentieEvContouren 'OpstelplaatsVoertuig'/ 'Vulpunt' worden de afstanden voor de EV contouren bepaald door tabel 4.899 uit het BAL;
- Een van de attributen die deze afstanden bepaalt is in deze tabel: 'inhoud opslagtank';
- 'Inhoud' is een attribuut van een 'OpslagReferentie' (opslagtank), maar niet van een 'Vulpunt' of 'OpstelplaatsVoertuig';
- Het is niet logisch om de waarde van een attribuut  (inhoud) van de ene referentieEvContour (opslagreferentie) toe te passen voor de bepaling van de afstanden voor de EV contour van een andere referentie ('sibling': Vulpunt, OpstelplaatsVoertuig); 
- Het is niet handig om het attribuut 'inhoud'  toe te voegen aan een 'OpstelplaatsVoertuig' of 'Vulpunt'. Dit werkt namelijk niet voor alle EV activiteiten.

![image](https://user-images.githubusercontent.com/115161221/231193862-33f9c60d-4e0f-405c-b8b2-81586ec2217f.png)

## Voorgestelde wijziging

Voeg het attribuut 'inhoud' in het IMEV toe aan  'OpslagtankPropaanPropeenVasteAfstand_GeenVergunningplicht'.
![image](https://user-images.githubusercontent.com/80040145/234587855-c1e15825-f10c-411c-ad19-cd2718e4cf6b.png)

## Impactanalyse

- Wie gaat er wat van merken? **Dataleveranciers en softwareleveranciers.**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
- Heeft het impact op het json-schema? **Ja, want extra attribuut**

## Prioriteit
middel

**Comment by PeterFrans** [comment]
![image](https://user-images.githubusercontent.com/115161221/231199911-166e9dd9-29f0-4e94-b753-ae6ceade0d7d.png)

(NB: dit is min of meer het omgekeerde van https://github.com/Geonovum/imev-werkomgeving/issues/41)

**Comment by JanCasSmitGeonovum** [comment]
Expert overleg IMEV 31 MEI 2023, thema Inhoud van het REV

Voorgestelde wijziging inhoudelijk akkoord? 1. Als we het doen, dan als afgeleid gegeven. 2. wel eerst voor de expertgroep REV laten beoordelen.

1.	Wat adviseren we de adviesgroep: eerst nog verder uitzoeken
2.	Wat is de prioriteit (hoog)
3.	Klopt de beschreven impact (Ja en wordt een Y wijziging.) wel extra impact voor REV i.v.m. oude data

Moeten software leveranciers benaderd worden voor dit issue: we moeten dit de leveranciers voorleggen

**Comment by PB-GNM** [comment]
De REV-expertgroep heeft in het overleg van 8-8-2023 aangegeven dat:

- er meerdere OpslagReferenties voor kunnen komen per activiteit. Er is 1 activiteit voor 1 vergunning, maar die kan dus meerdere OpslagReferenties bevatten.
- Het automatisch afleiden van het totaal kan niet, want alleen de afzonderlijke inhoud van de Opslagreferenties geven zinnige informatie. De som zegt niet veel want de onderlinge afstand van de OpslagReferenties doet er ook toe.
- Daarnaast is er ook de mogelijkheid van het opgeven van een SamengesteldeReferentie en die kan ook inhoud hebben, maar is geen onderdeel van dit objecttype.
- Als er toch iets nodig zou zijn per activiteit, dan zou dat met een categorie indeling moeten. Die is er niet, dus als dat gewenst is moet er een afzonderlijke wijzigingsverzoek voor worden ingediend.
- Het advies is dus niet doen.

**Comment by PB-GNM** [comment]
Adviesgroep 13-9-2023 heeft besloten deze wijziging niet door te voeren.
