### ISSUE TITLE
'geometrieDeuropening' bij 'OpslagVuurwerkF1F2F3T1T2'

### ISSUE THREAD

**Issue by PeterFrans** [Geonovum/imev-werkomgeving#89]
## Aanleiding

Achtergrond

- In het IMEV 1.3 kan een 'Bufferbewaarplaats' onderdeel zijn van een 'OpslagVuurwerkF1F2F3T1T2'.

In **bijlage VII B bij artikel 5.23 van het BKL** staat beschreven hoe een explosieAandachtsgebied vuurwerk voor opslag van vuurwerk van categorie F1, F2 of F3 of pyrotechnische artikelen voor theatergebruik van categorie T1 of T2 bepaald moet worden. In de bijbehorende figuur worden een aantal parameters gegeven (a, b, c). De breedte van de deur van de opslag ontbreekt hier, maar is wel nodig voor de berekening van het explosieAandachtsgebied.

![image](https://user-images.githubusercontent.com/115161221/218746906-38fbf0c7-a05e-40cd-bb20-3fac521a9b32.png)

Wat is het probleem?

1. Omdat de breedte van de deur niet is opgenomen in het BKL en IMEV, is het niet mogelijk om zonder impliciete aannames het explosieAandachtsgebiedVuurwerk te berekenen zoals beschreven in het BKL (zie hierboven);
2. Er is geen richting van de breedte van de deuropening (geometrie) beschikbaar.

Samengevat:

Het IMEV 1.3 bevat onvoldoende gegevens om een ExplosieAandachtsgebiedVuurwerk voor een Bufferbewaarplaats bij 'OpslagVuurwerkF1F2F3T1T2' te berekenen zonder impliciete aannames.

## Voorgestelde wijziging

Om het explosieAandachtsgebied zonder impliciete aannames te kunnen berekenen, is het goed om de volgende attributen toe te voegen aan de BufferBewaarplaats:

+ richtingVoorwaarts: Real (graden)
+ afstandVoorwaarts: Real (m)
+ afstandZijwaarts: Real (m)
+ afstandAchterwaarts: Real (m)
+ deurbreedte: Real (m)

Hierbij komen de 3 afstanden overeen met de paramaters a, b en c  (zie bijgevoegde figuur). 
Deze attributen zouden verplicht moeten zijn.

De situatie was:
![image](https://user-images.githubusercontent.com/80040145/231479664-95239281-ac55-4703-96d4-45133c2b8f34.png)
De situatie wordt:
![image](https://user-images.githubusercontent.com/80040145/231758688-955569d3-07f1-4702-9e59-a88649c84614.png)

## Impactanalyse

- Wie gaat er wat van merken? **Dataleveranciers en softwareleveranciers.**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
- Heeft het impact op het json-schema? **Ja, want extra attribuut**

## Prioriteit
middel

## Toelichting
Er speelt een fundamentele vraag net als in #41 en #94:
a)	Is het IMEV bedoeld om de gegevens van de EV contouren te delen inclusief een aantal gegevens die nodig zijn als basisgegeven bij de EV contour?
b)	Is het IMEV bedoeld om de gegevens van de EV contouren te delen inclusief alle gegevens die nodig zijn om de contour te berekenen?
Het uitgangspunt voor het IMEV is altijd het BKL. Dus alleen gegevens die voor het REV gevraagd worden in het BKL horen thuis in het IMEV.  Dit zal dus eerst per geval bekeken moeten worden.

**Comment by PB-GNM** [comment]
Hoi Peter Frans,

We merken dat je afgelopen maand veel issues hebt ingediend via Github.
Op zich heel fijn dat je betrokken bent, maar zou je die meldingen voortaan willen sturen via mail naar de helpdesk:  imev@geonovum.nl.

De helpdesk houden we namelijk in de gaten en Github minder. Daarom reageer ik ook nu pas. 
Als wij het dan binnen krijgen in de helpdesk, beoordelen wij of het een bug dan wel wijzigingsverzoek is. Als het ons helemaal duidelijk is wat er aan de hand is plaatsten wij het op Github voor discussie met experts. Daar is het aan iedereen vrij om er op te reageren.

Ook kunnen we jou dan directer benaderen, want we weten jouw contactgegevens nu niet.
Zou je die contactgegevens voor ons alsnog willen mailen via imev@geonovum.nl, want dan kan ik je direct op de hoogte houden van de status van de meldingen en eventueel ook uitnodigen voor expertgroep vergaderingen waarin we de wensen inhoudelijk bespreken.

Voor nu hoef je niet met terugwerkende kracht alles te melden in de helpdesk, maar in de toekomst dus graag wel.
De structuur van Github helpt ons al wel bij je aanmelding van issues, dus die kan je ook gebruiken in de mails naar de helpdesk.

Met vriendelijke groet,
Pieter Bresters
Geonovum

**Comment by PeterFrans** [comment]
Wanneer alle parameters van een explosieAandachtsgebiedVuurwerk wiorden toegevoegd aan het IMEV, dan kan dit verzoek vervallen (verzoek om alle parameters op te nemen per 7-4-2023 nog niet verwerkt tot een 'issue' hier).

**Comment by PeterFrans** [comment]
Uit bijlage VIII B van het BKL (zie onder) blijkt dat de parameters die nodig zijn om een 'paddenstoelvormig' explosieAandachtsgebiedVuurwerk te berekenen alleen nodig zijn voor een 'Bufferbewaarplaats' (bij 'OpslagF1F2F3T1T2'). 

Voor een 'Bewaarplaats' (en een 'Bewerkingsruimte') is er maar 1 afstand, wat resulteert in een cirkelvormig explosieAandachtsgebied.

Het lijkt me goed de voorgestelde parameters verplicht te maken bij een 'Bufferbewaarplaats', zodat bij verplaatsing van de referentieEVContour het explosieAandachtsgebiedVuurwerk eenvoudig via het API endpoint herberekend kan worden.

![image](https://user-images.githubusercontent.com/115161221/231553924-f7ba01c1-a820-4235-92d4-8df1428a1953.png)

**Comment by PB-GNM** [comment]
Bovenstaande toevoeging is verwerkt in https://github.com/Geonovum/imev-werkomgeving/issues/89#issue-1574515840.

**Comment by JanCasSmitGeonovum** [comment]
Expert overleg IMEV 31 MEI 2023, thema Inhoud van het REV

Voorgestelde wijziging inhoudelijk akkoord? Vraag wordt meegenomen door naar IenW voor de fundamentele discussie moet het REV rekenen of niet. Tot dan doen we dit niet.

1.	Wat adviseren we de adviesgroep: nu niet doen zie boven
2.	Wat is de prioriteit (leeg, middel, hoog) als optioneel dan Y als verplicht, dan X wijziging.
3.	Klopt de beschreven impact (Ja)

Moeten software leveranciers benaderd worden voor dit issue: nog niet, eerst discussie IenW afwachten

**Comment by PB-GNM** [comment]
De REV-expertgroep heeft in het overleg van 8-8-2023 aangegeven dat:

- Zie #94

**Comment by PB-GNM** [comment]
Adviesgroep 13-9-2023 heeft besloten deze wijziging niet door te voeren, want er is geen wettelijke basis om dit te doen.
Wel is er gesproken over het nader onderzoeken van het conceptuele achter dit issue.
