### ISSUE TITLE
Opnemen verschillende enumeraties voor OpslagVuurwerkF4 en OpslagVuurwerkF1F2F3T1T2

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#91]
## Aanleiding wijziging
In het IMEV 1.3 bestaan o.a. de volgende objecttypen:

1. OpslagVuurwerkF4 (VIII-A Explosieaandachtsgebied vuurwerk voor opslag van categorie F4);
2. OpslagVuurwerkF1F2F3T1T2 (VIII-B Explosieaandachtsgebied vuurwerk voor opslag van categorie F1, F2, F3, of pyrotechnische artikelen voor theatergebruik van categorie T1 of T2).

Beide objecten hebben de enumeratie ' CategorieVuurwerk' met de waarden:

- T1;
- T2;
- F1;
- F2;
- F3;
- F4;
- gegevenInTransitie.

Als gevolg hiervan is het bijvoorbeeld toegestaan om in het REV de 'OpslagVuurwerkF4' met  elke waarde uit de enumeratie 'CategorieVuurwerk' op te voeren, zoals 'T1'.
Dit is onjuist en komt de kwaliteit van de REV data niet ten goede.

## Voorgestelde wijziging

1. Neem een aparte enumeratie op in het IMEV voor 'Opslag-Vuurwerk-F4': ' CategorieVuurwerkF4' met cardinaliteit 0..1 en de waarde:

- F4.
- gegevenInTransitie

2. Neem een aparte enumeratie op in het IMEV voor 'Opslag-Vuurwerk-F1F2F3T1T2':  'CategorieVuurwerkF1F2F3T1T2' met cardinaliteit 0 .. * en de waarden:

- F1;
- F2;
- F3;
- T1;
- T2;
- gegevenInTransitie.

3. Laat de enumeratie ' CategorieVuurwerk' vervallen.

## Impactanalyse

- Wie gaat er wat van merken? **Dataleveranciers van buisleidingen, Softwareleveranciers**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
- Heeft het impact op het json-schema? **Ja**
- Is het backwardscompatibel? **Nee**
- X-, Y- of Z-wijziging: **X**

## Prioriteit
midden

## Toelichting
Ruimte voor extra toelichting. Bijvoorbeeld alternatieven die je overwogen hebt.

**Comment by PeterFrans** [comment]
Bij nader inzicht is het beter om:

1. Het attribuut 'CategorieVuurwerk' voor 'OpslagVuurwerkF4' te laten vervallen. Voor deze activiteit is de categorie altijd 'F4' en is 'gegevenInTransitie' dus ook niet van toepassing.
2. De enumerable voor  'CategorieVuurwerk' voor 'OpslagVuurwerkF1F2F3T1T2' aan te passen: F4 hieruit verwijderen en de kardinaliteit aanpassen naar [1 .. 5]. Er zal altijd een categorie gekozen moeten worden, en er zijn maximaal 5 verschillende categorieen te selecteren (het heeft geen zin 1 categorie meerdere keren toe te voegen, of alle 5 de categorieen icm 'gegevenInTransitie' op te voeren).

**Comment by PB-GNM** [comment]
In de expertgroep van 17 mei is besloten om dit uit te voeren.
In de praktijk bleek dit al doorgevoerd in de API.
Er is dus eigenlijk geen impact.

**Comment by PB-GNM** [comment]
In #94 is voorgesteld om categorie F4 helemaal weg te laten. Ook als attribuut bij de activiteit OpslagVuurwerkF4.
In de expertgroep is besloten dit deel van #94 door te voeren en dat kan dan gelijk met deze.

**Comment by PB-GNM** [comment]
Opgelost in [versie 2.0](https://docs.geostandaarden.nl/imev/def-im-imev-20231031/).
