### ISSUE TITLE
Bewoording van enumeratie niet consequent

### ISSUE THREAD

**Issue by idekkerkza** [Geonovum/imev-werkomgeving#93]
## Waar zit de fout?

6.1.10 VII-A.7 Opslaan van propaan of propeen in opslagtanks. Bij enumeratie: CategorieAantalBevoorradingen
![image](https://user-images.githubusercontent.com/126789579/222692657-3d44dff6-160b-4e31-a0c2-b8e061693528.png)

## Wat is de fout?

Aantal bevoorradingen bij A7 optie keuze: ‘groter dan vijf’, ‘kleiner of gelijk vijf’. De bewoording is hier niet helemaal logisch. Dit zou iets netter kunnen. 

## Wat moet het worden? [optioneel]

Bijvoorbeeld: ‘meer dan 5’, ‘minder of gelijk aan 5’

**Comment by PB-GNM** [comment]
Beste I Dekker,
Dank voor de melding en het meedenken.
Het klopt dat de Github pagina open staat voor iedereen, maar we hebben liever dat als men iets wil melden dat dat dan via de mail gaat naar IMEV@Geonovum.nl. Geonovum zet daarna het wijzigingsverzoek of de bug op Github. Daarna is het juist wel de bedoeling dat er gereageerd wordt via Github zodat iedereen er over mee kan discussiëren.

Taalkundig ben ik het niet eens met deze gemelde bug.
Je zegt niet "het aantal is meer geworden" maar wel "het aantal is groter geworden". Het gaat hier over een Aantal.
Als er niet zo specifiek "Aantal" in de naam van het objecttype had gestaan was "meer" wel beter geweest.
Je zegt wel "er zijn meer bevoorradingen".

Ik hoop dat je na deze motivatie het hiermee eens bent en voel je vrij om er weer op te reageren via Github.
Dan geef ik hem daarna het label "won't fix".

**Comment by idekkerkza** [comment]
Beste Pieter, 

Bedankt voor jouw reactie. 
Wijzigingsverzoeken zal ik in het vervolg via het opgegeven e-mailadres doorzetten. Ik mis dit echter in de readme.md en was hierdoor niet op de hoogte. Zou dit in de readme.md verwerkt kunnen worden? 

Bedankt ook voor de uitleg, ik begrijp nu waarom hiervoor is gekozen. De bewoording: 'Kleiner of gelijk vijf' is alleen, als gebruiker bij het invoeren, niet helemaal logisch. Hier zou je 'Kleiner of gelijk aan vijf' verwachten. Misschien kan deze wijziging meegenomen worden, anders houden wij het op 'won't fix'. 

Vriendelijke groeten,
Isabeau Dekker

**Comment by PB-GNM** [comment]
Hoi Isabeau,

Dan zou het moeten worden "Kleiner dan of gelijk aan vijf".
Hier gaan we nog over nadenken.

Omdat je niet de eerste bent die zelfstandig issues heeft aangemaakt, heb ik het nu in de templates verwerkt die je te zien krijgt wanneer je een nieuw issue probeert aan te maken.
Helaas is er op de issue pagina geen manier om een readme.md op te nemen.
Op de home pagina https://github.com/Geonovum/imev-werkomgeving/ kan dit wel.
Dus daar ga ik het ook nog opnemen. Bedankt voor deze tip.

**Comment by idekkerkza** [comment]
Hoi Pieter, 

Dat is goed. 
Super dat het nu verwerkt is in de templates en in de readme.md op de home pagina. 

Vriendelijke groeten,
Isabeau Dekker

**Comment by PeterFrans** [comment]
Misschien is het het beste om een zo consistent mogelijke schrijfwijze toe te passen binnen het IMEV? Mijn voorkeur zou bijvoorbeeld zijn:

**Voordruk**

- $\lt$ 420 kPa
- $\ge$  420 kPa

**Categorie aantal bevoorradingen**

- $\le$  5
- $\gt$ 5

**reactietijdNoodstop**

- $\le$  5 s
- $\gt$ 5 s

**hoeveelheidsklasse stikstofgehalte**

- [N2] $\lt$  5%
- 5% $\le$ [N2] $\le$ 10%
- [N2] $\gt$  10%

**Comment by PB-GNM** [comment]
## Aanleiding wijziging
De waardes in de enumeraties voor hoeveelheden en groothedenzijn niet consequent.

## Voorgestelde wijziging
Voordruk

 420 kPa
 420 kPa
Categorie aantal bevoorradingen

 5
 5
reactietijdNoodstop

 5 s
 5 s
hoeveelheidsklasse stikstofgehalte

[N2] 
 5%
5% 
 [N2] 
 10%
[N2] 
 10%

## Impactanalyse
- Wie gaat er wat van merken? **Dataleveranciers, Softwareleveranciers**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
- Heeft het impact op het json-schema? **Ja, want enumeraties worden aangepast**
- Is het backwardscompatibel? **Nee**
- X-, Y- of Z-wijziging: **Y**

## Prioriteit
laag

**Comment by PalmJanssen** [comment]
De < en > dan tekens geven een probleem in de modelleertooling. Op zich niet zo netjes en ik zal eens kijken wat we daar aan kunnen doen.

**Comment by PB-GNM** [comment]
In de expertgroep van 17 mei is besloten om te adviseren om dit wijzigingsverzoek niet uit te voeren, omdat de impact groot is en het voordeel minimaal. Tevens voorkomt dat problemen zoals in bovenstaande comment genoemd.

**Comment by PB-GNM** [comment]
Tijdens het softwareleveranciersoverleg van 7 juni is er geen bezwaar geuit tegen het niet doorvoeren van deze wijziging.

**Comment by PB-GNM** [comment]
Adviesgroep 13-9-2023 heeft besloten deze wijziging niet door te voeren.
