### ISSUE TITLE
Attribuut hoeveelheidVuurwerk verplaatsen van subtypes van BKLActiviteit naar nieuwe subtypes van ReferentieEVContour (SDIMEV-75)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#94]
## Aanleiding wijziging
Het gaat om het attribuut ‘hoeveelheidVuurwerk’ op de volgende twee activiteiten:  

· VIII-A Explosieaandachtsgebied vuurwerk voor opslag van categorie F4 – detail  
· VIII-B Explosieaandachtsgebied vuurwerk voor opslag van categorie F1, F2, F3, of pyrotechnische artikelen voor theatergebruik van categorie T1 of T2 - detail 

Het attribuut ‘hoeveelheidVuurwerk’ wordt uitgevraagd op activiteit niveau. Als gebruiker geef je hier als het ware een totale hoeveelheid vuurwerk van alle bewaarplaatsen, bufferbewaarplaatsen en/of bewerkingsruimten op één locatieactiviteit. Dit is voor de gebruiker van de Invoer Module niet gewenst.  

Bijvoorbeeld: Het is mogelijk dat er 2 buffers staan op 1 locatieactiviteit. 1 buffer bevat 500 kg vuurwerk en 1 buffer bevat 1000 kg vuurwerk. Op dit moment moet je het getal 1500 invoeren op activiteitniveau. Als gebruiker wil je deze aantallen opvoeren per buffer.

## Voorgestelde wijziging
Attribuut hoeveelheidVuurwerk verplaatsen van subtypes voor opslag van vuurwerk van het abstracte type _BKLActiviteit_ naar (nieuwe) subtypes van ReferentieEVContour. In geval van Bewaarplaats en SamengesteldeReferentie moeten het nieuwe referentie types worden, want de oude worden ook voor andere activiteiten dan vuurwerkopslag gebruikt. Bufferbewaarplaats en Bewerkingsruimte kunnen hetzelfde objecttype blijven omdat die volgens de definitie specifiek voor vuurwerkopslag zijn.

![image](https://user-images.githubusercontent.com/80040145/223678826-58042588-0614-44d5-b4c7-1d3a0c83b8ca.png)

## Impactanalyse

- Wie gaat er wat van merken? **Dataleveranciers, Softwareleveranciers**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Ja**
- Heeft het impact op het json-schema? **Ja**
- Is het backwardscompatibel? **Nee**
- X-, Y- of Z-wijziging: **X** Voor bestaande data moet bedacht worden hoe de hoeveelheden verdeeld worden over meerdere bewaarplaatsen.

## Prioriteit
midden

## Toelichting
Er speelt een fundamentele vraag net als in #41 en #89:
a)	Is het IMEV bedoeld om de gegevens van de EV contouren te delen inclusief een aantal gegevens die nodig zijn als basisgegeven bij de EV contour?
b)	Is het IMEV bedoeld om de gegevens van de EV contouren te delen inclusief alle gegevens die nodig zijn om de contour te berekenen?
Het uitgangspunt voor het IMEV is altijd het BKL. Dus alleen gegevens die voor het REV gevraagd worden in het BKL horen thuis in het IMEV.  Dit zal dus eerst per geval bekeken moeten worden.

**Comment by PeterFrans** [comment]
Dit is niet de juiste oplossing voor het probleem. Het probleem is dat er twee hoeveelheden vuurwerk nodig zijn in het IMEV:

1. De totale hoeveelheid vuurwerk op de EV locatie. Dit is het attribuut 'hoeveelheidVuurwerk'  bij OpslagVuurwerkF4 en OpslagVuurwerkF1F2F3T1T2: '_hoeveelheid consumentenvuurwerk in de inrichting: sommatie van de aanwezige hoeveelheid consumentenvuurwerk in de bewaarplaats, de bufferbewaarplaats en de verkoopruimte, uitgedrukt in kilogrammen'_ (Vuurwerkbesluit, artikel 1.1.1 lid 2e). Deze som van de hoeveelheid wordt gebruikt om te bepalen of de EV locatie vergunningsplichtig is ( >10.000 kg F1F2F3 is vergunningsplichtig, zie Besluit Activiteiten Leefomgeving (BAL) artikel 3.31, lid 1b).
2. De toegestane hoeveelheid vuurwerk in een bufferbewaarplaats. Dit attribuut bestaat nog niet in het IMEV maar hoort bij de bufferbewaarplaats opgenomen te worden. In het BAL (tabel 4.1036b) heeft het de omschrijving: _Toegestane hoeveelheid vuurwerk van categorie F1, F2 of F3 en pyrotechnische artikelen voor theatergebruik in bufferbewaarplaats in kg_ . Deze hoeveelheid wordt gebruikt om de veiligheidsafstanden rondom de bufferbewaarplaats vast te stellen (vuurwerkbesluit bijlage 3B Veiligheidsafstanden, artikel 1.3c)

Ik stel dus voor

1. om het attribuut 'hoeveelheidVuurwerk':

- Niet te verplaatsen maar te behouden bij: OpslagVuurwerkF4 en OpslagVuurwerkF1F2F3T1T2;
- Het voor een duidelijk onderscheid te hernoemen naar: 'somHoeveelheidVuurwerkLocatie';
- De definitie aan te passen van '_Hoeveelheid vuurwerk (als Netto Explosieve Massa in kg)_' naar '_hoeveelheid consumentenvuurwerk in de inrichting: sommatie van de aanwezige hoeveelheid consumentenvuurwerk in de bewaarplaats, de bufferbewaarplaats en de verkoopruimte, uitgedrukt in kilogrammen'_ .

2. om het attribuut 'toegestaneHoeveelheidVuurwerkBewaarplaats':

- Toe te voegen in het IMEV bij een 'Bufferbewaarplaats';
- Te overwegen om het ook op te nemen bij een 'Bewaarplaats', zodat de som uitgerekend kan worden (ik heb nergens kunnen vinden dat een 'Bewerkingsruimte' ook voor opslag gebruikt mag worden);
- Te voorzien van de definitie: _Toegestane hoeveelheid vuurwerk van categorie F1, F2 of F3 en pyrotechnische artikelen voor theatergebruik in bufferbewaarplaats in kg_

**Comment by PeterFrans** [comment]
Verder valt te overwegen om voor 'hoeveelheidVuurwerkBewaarplaats' een enumeratie op te nemen:

![image](https://user-images.githubusercontent.com/115161221/229605882-0677dd93-85b1-497a-931e-cdb2d0c8e6ca.png)

**Comment by PeterFrans** [comment]
Het is te overwegen om de hier voorgestelde 'verkoopruimte' niet op te nemen. Buiten openingstijden mag er maar 200 kg F1 liggen (20 kg F2F3 equivalent), de rest (max 500 kg) moet dan in de bewaarplaats zitten.  Voor de totale hoeveelheid op de locatie is de hoeveelheid van 20 kg niet erg relevant, waarschijnlijk binnen de foutenmarge. Wanneer er alleen 200 kg F1 op een locatie ligt, is dit geen MBA.

NB: De definitie van de 'hoeveelheidVuurwerkLocatie' moet dan aangepast worden.

**Comment by PeterFrans** [comment]
Het opnemen van het attribuut 'hoeveelheidVuurwerkBewaarplaats' en 'hoeveelheidNEMBewaarplaats' is belangrijk: Op basis van deze hoeveelheden worden vaak de afstanden (voorwaards, zijwaards, achterwaards) van het 'explosieAandachtsgebiedVuurwerk' rondom de risicobron (inrichtingselement) bepaald.

**Comment by PB-GNM** [comment]
## Aanleiding wijziging
Het gaat om het attribuut ‘hoeveelheidVuurwerk’ op de volgende twee activiteiten:  

· VIII-A Explosieaandachtsgebied vuurwerk voor opslag van categorie F4 – detail  
· VIII-B Explosieaandachtsgebied vuurwerk voor opslag van categorie F1, F2, F3, of pyrotechnische artikelen voor theatergebruik van categorie T1 of T2 - detail 

Het attribuut ‘hoeveelheidVuurwerk’ wordt uitgevraagd op activiteit niveau. Als gebruiker geef je hier als het ware een totale hoeveelheid vuurwerk van alle bewaarplaatsen, bufferbewaarplaatsen en/of bewerkingsruimten op één locatieactiviteit. Dit is voor de gebruiker van de Invoer Module niet gewenst.  

Bijvoorbeeld: Het is mogelijk dat er 2 buffers staan op 1 locatieactiviteit. 1 buffer bevat 500 kg vuurwerk en 1 buffer bevat 1000 kg vuurwerk. Op dit moment moet je het getal 1500 invoeren op activiteitniveau. Als gebruiker wil je deze aantallen opvoeren per buffer.

## Voorgestelde wijziging


## Impactanalyse

- Wie gaat er wat van merken? **Dataleveranciers, Softwareleveranciers**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Ja**
- Heeft het impact op het json-schema? **Ja**
- Is het backwardscompatibel? **Nee**
- X-, Y- of Z-wijziging: **X** Voor bestaande data moet bedacht worden hoe de hoeveelheden verdeeld worden over meerdere bewaarplaatsen.

## Prioriteit
midden

## Toelichting
Er speelt een fundamentele vraag net als in #41 en #89:
a)	Is het IMEV bedoeld om de gegevens van de EV contouren te delen inclusief een aantal gegevens die nodig zijn als basisgegeven bij de EV contour?
b)	Is het IMEV bedoeld om de gegevens van de EV contouren te delen inclusief alle gegevens die nodig zijn om de contour te berekenen?
Het uitgangspunt voor het IMEV is altijd het BKL. Dus alleen gegevens die voor het REV gevraagd worden in het BKL horen thuis in het IMEV.  Dit zal dus eerst per geval bekeken moeten worden.

**Comment by JanCasSmitGeonovum** [comment]
Expert overleg IMEV 31 MEI 2023, thema Inhoud van het REV

Voorgestelde wijziging inhoudelijk akkoord? Ja/nee

wel hoeveelheden en wel categorieën niet namen objecttype en niet object toevoegen.
er wordt nog een veld afgeleid (pieter voegt aan)
 
1.	Wat adviseren we de adviesgroep: wel doen, maar anders
2.	Wat is de prioriteit (hoog)  is een X wijziging, verplicht invoeren van gegevens.
3.	Klopt de beschreven impact (Ja)

Moeten software leveranciers benaderd worden voor dit issue; bij X wijziging zo wie zo bespreken.

**Comment by PB-GNM** [comment]
De REV-expertgroep heeft in het overleg van 8-8-2023 aangegeven over het opnemen van het extra attribuut hoeveelheid dat:

- het inconsequent is om de hoeveelheid hier niet op te nemen per referentie object, omdat het bv bij OpslagReferentie wel gedaan wordt via attribuut inhoud.
- het goed is voor de datakwalitiet als de hoeveelheid hier opgenomen wordt per referentie object, want dan kan de contour getoetst worden.
- Volgens de wet hoeft het niet voor deze activiteit, maar wel voor andere. De wet is dus inconsequent. 
- De fundamentele vraag als gesteld in de toelichting van https://github.com/Geonovum/imev-werkomgeving/issues/94#issuecomment-1523464732 moet eerst beantwoord worden voordat hier een keuze gemaakt kan worden.
- Bij samengestelde referentie moet het zo wie zo niet opgenomen worden, want die is juist bedoeld voor als de exacte gegevens per referentieobject bv niet openbaar gedeeld kunnen worden.

**Comment by PB-GNM** [comment]
Tijdens de REV-expert bijeenkomst van 8-6 is het volgende gezegd:
Alleen de categorie aanpassen in lijn met github issue #91.
Voor de toe te voegen attributen over hoeveelheid moet eerst de fundamentele vraag beantwoord worden of REV bedoeld is om contouren te kunnen berekenen of niet. Zie ook Github issue #89.
De totale hoeveelheid kan niet afgeleid worden uit de afzonderlijke hoeveelheden.
