### ISSUE TITLE
Extra attribuut voor bronhoudercode aansluitend op DSO

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/imev-werkomgeving#99]
## Aanleiding wijziging
Op dit moment is niet duidelijk in de definitie welke code er precies ingevuld moet worden, waardoor het niet goed aansluit op het DSO en niet duidelijk is wat er voor code ingevuld moet worden.

## Voorgestelde wijziging
Neem op in de definitie dat hier de codelijsten gebruikt moeten worden die te vinden zijn op :
https://standaarden.overheid.nl/tooi/waardelijsten/
Voor Gemeenten de meest actuele versie van:
https://standaarden.overheid.nl/tooi/waardelijsten/expression?lijst_uri=https%3A%2F%2Fidentifier.overheid.nl%2Ftooi%2Fset%2Frwc_gemeenten_compleet%2F4 
Voor Omgevingsdiensten de meest actuele versie van:
https://standaarden.overheid.nl/tooi/waardelijsten/expression?lijst_uri=https%3A%2F%2Fidentifier.overheid.nl%2Ftooi%2Fset%2Frwc_samenwerkingsorganisaties_compleet%2F1

Het voordeel van dit wijzigingsverzoek is dat deze code hiermee dicht bij de Bron komt (BZK via Koop) waardoor het actueel is. Daarnaast sluit het aan op wat er binnen de DSO gebruikt wordt en met wat er door CBS gebruikt wordt.
Voorgesteld wordt om daarbij ook het formeel patroon op te nemen waardoor er geen vreemde codes ingevoerd kunnen worden.

## Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? **Dataleveranciers**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Ja, de definitie van de code wordt aangepast**
- Heeft het impact op het json-schema? **Nee**
- Is het backwardscompatibel? **Niet wat betreft oude aangeleverde bestanden waarin nog oude codes zijn opgegeven**
- X-, Y- of Z-wijziging: **Y**

## Prioriteit
midden

## Toelichting
Dit voorstel verhoogt de datakwaliteit.
Als alternatief kan het OIN register gebruikt worden. Zie overweging: https://github.com/Geonovum/imev-werkomgeving/issues/99#issuecomment-2056360301

**Comment by PB-GNM** [comment]
Nog even 2 opmerkingen
•	Het zou handig zijn als er een permanente link naar een een 'latest' versie is die altijd de meest recente codes laat zien? Nu moet je periodiek de nieuwste versie aanklikken. Een alternatief is om te verwijzen naar https://standaarden.overheid.nl/tooi/waardelijsten/work?work_uri=https://identifier.overheid.nl/tooi/set/rwc_gemeenten_compleet met de opmerking dat je daar de meest recente moet nemen.
•	Het lijkt ook goed om de naam (schrijfwijze) over te nemen uit deze waardelijsten.

**Comment by PB-GNM** [comment]
Bij een vergelijk van verschillende informatiemodellen voor IBP VTH, is een verschil opgevallen tussen STAM/ IMAM en IMOW als het gaat om gebruik van een identificatienummer van bevoegd gezag. In het REV zijn de omgevingsdiensten ook op verschillende manieren geregistreerd. Genoeg reden om hier voor één standaard te gaan.

Hieronder is een link die aangeeft hoe het in de BRK geregeld is voor gemeenten, provincies, waterschappen en landen: 
https://brk.basisregistraties.overheid.nl/bestuurlijke-grenzen-api#/paths/~1openbare-lichamen/get .
Dit komt overeen met het organisatie type en de organisatie code zoals gebruikt wordt in het  ([OIN](https://oinregister.logius.nl/)). Het OIN Register geeft een overzicht van alle uitgegeven openbare Organisatie Identificatienummers waar deze organisatie type en de organisatie code aan gekoppeld zijn.
Voor de omgevingsdiensten gebruikt het OIN het organisatietype 'GR', met en zonder voorloop 0:
bv: **GR892** voor Omgevingsdienst Twente en **GR0721** voor Omgevingsdienst Groningen.

Dit komt maar deels overeen met https://standaarden.overheid.nl/tooi/waardelijsten/expression? zoals in het oorspronkelijke wijzigingsverzoek is beschreven: lijst_uri=https%3A%2F%2Fidentifier.overheid.nl%2Ftooi%2Fset%2Frwc_samenwerkingsorganisaties_compleet%2F1, want daarin hebben ze de volgende coderingen gebruikt: **[so0892](https://identifier.overheid.nl/tooi/id/so/so0892)** voor Omgevingsdienst Twente en **[so0721](https://identifier.overheid.nl/tooi/id/so/so0721)** voor Omgevingsdienst Groningen.
Verschillen zitten in:
-voorloopnul
-verschillende organisatie types **GR** of **so**
-hoofdlettters en kleine letters

**Comment by JanCasSmitGeonovum** [comment]
Na analyse en discussie gekozen om voor overheden en samenwerkingsorganisaties / gemeenschappelijke regelingen te gaan voor TOOI. Hier is sprake van een bronhouders-code die uit 1 set karakters bestaat. Bij OIN zijn het 3 afzonderlijke  karaktersets.

Het wordt een nieuw attribuut dat nodig is omdat er sprake zal zijn van een overgangssituatie. 
Voor niet overheidsorganisaties houden we voorlopig nog vast aan de bestaande bronhoudercodes die in het REV zijn verwerkt. Er gaat uitgezocht worden hoe voor deze groep in de toekomst een correcte bronhouders-code kan worden bepaald. 
dit houdt dan in dat voorlopig ruim 20% van de objecten (buisleidingreferenties) RRGS als bronhouders-code heeft.

**Comment by PB-GNM** [comment]
Voorstel naam nieuwe attribuut: bronhoudercode_Overheid
In de toelichting komt te staan dat deze gevuld moet worden vanuit de hierboven genoemde Tooilijsten.
Indien geen overheid, dan een code uit een nieuw te maken waardelijst (Bronhoudercode_nietOverheid) waarbij gebruikt gemaakt wordt van de codes zoals die nu ook gebruikt worden voor het attribuut bronhoudercode.

**Comment by PB-GNM** [comment]
Daarnaast is er dan ook een nieuw attribuut nodig voor bronhoudercode_NietOverheid.
Er moet dan nog een regel/constraint bij dat één van de twee gevuld moet zijn.

**Comment by PB-GNM** [comment]
Aandachtspunten vanuit de consultatie (5-9-2024) :

- De huidige bronhoudercode zit ook verwerkt in de identificatie van alle objecten. Het uitfaseren van de huidige bronhoudercode zal daarom ook voor volgende versies heroverwogen moeten worden.
